version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  ignore:
  - dependency-name: k8s.io/*
    update-types:
    - version-update:semver-patch
- package-ecosystem: gomod
  directory: "/cmd/diegen"
  schedule:
    interval: daily
