//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021-2022 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	metav1 "dies.dev/apis/meta/v1"
	json "encoding/json"
	fmtx "fmt"
	batchv1 "k8s.io/api/batch/v1"
	corev1 "k8s.io/api/core/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	jsonpath "k8s.io/client-go/util/jsonpath"
	osx "os"
	reflectx "reflect"
	yaml "sigs.k8s.io/yaml"
)

var CronJobBlank = (&CronJobDie{}).DieFeed(batchv1.CronJob{})

type CronJobDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       batchv1.CronJob
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *CronJobDie) DieImmutable(immutable bool) *CronJobDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *CronJobDie) DieFeed(r batchv1.CronJob) *CronJobDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &CronJobDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *CronJobDie) DieFeedPtr(r *batchv1.CronJob) *CronJobDie {
	if r == nil {
		r = &batchv1.CronJob{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *CronJobDie) DieFeedJSON(j []byte) *CronJobDie {
	r := batchv1.CronJob{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *CronJobDie) DieFeedYAML(y []byte) *CronJobDie {
	r := batchv1.CronJob{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *CronJobDie) DieFeedYAMLFile(name string) *CronJobDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *CronJobDie) DieFeedRawExtension(raw runtime.RawExtension) *CronJobDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *CronJobDie) DieRelease() batchv1.CronJob {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *CronJobDie) DieReleasePtr() *batchv1.CronJob {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *CronJobDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *CronJobDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *CronJobDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *CronJobDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *CronJobDie) DieStamp(fn func(r *batchv1.CronJob)) *CronJobDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *CronJobDie) DieStampAt(jp string, fn interface{}) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *CronJobDie) DieWith(fn func(d *CronJobDie)) *CronJobDie {
	nd := CronJobBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *CronJobDie) DeepCopy() *CronJobDie {
	r := *d.r.DeepCopy()
	return &CronJobDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*CronJobDie)(nil)

func (d *CronJobDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *CronJobDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *CronJobDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *CronJobDie) UnmarshalJSON(b []byte) error {
	if d == CronJobBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &batchv1.CronJob{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *CronJobDie) APIVersion(v string) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *CronJobDie) Kind(v string) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *CronJobDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *CronJobDie) SpecDie(fn func(d *CronJobSpecDie)) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		d := CronJobSpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *CronJobDie) StatusDie(fn func(d *CronJobStatusDie)) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		d := CronJobStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

// Specification of the desired behavior of a cron job, including the schedule. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
func (d *CronJobDie) Spec(v batchv1.CronJobSpec) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		r.Spec = v
	})
}

// Current status of a cron job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
func (d *CronJobDie) Status(v batchv1.CronJobStatus) *CronJobDie {
	return d.DieStamp(func(r *batchv1.CronJob) {
		r.Status = v
	})
}

var CronJobSpecBlank = (&CronJobSpecDie{}).DieFeed(batchv1.CronJobSpec{})

type CronJobSpecDie struct {
	mutable bool
	r       batchv1.CronJobSpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *CronJobSpecDie) DieImmutable(immutable bool) *CronJobSpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *CronJobSpecDie) DieFeed(r batchv1.CronJobSpec) *CronJobSpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &CronJobSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *CronJobSpecDie) DieFeedPtr(r *batchv1.CronJobSpec) *CronJobSpecDie {
	if r == nil {
		r = &batchv1.CronJobSpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *CronJobSpecDie) DieFeedJSON(j []byte) *CronJobSpecDie {
	r := batchv1.CronJobSpec{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *CronJobSpecDie) DieFeedYAML(y []byte) *CronJobSpecDie {
	r := batchv1.CronJobSpec{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *CronJobSpecDie) DieFeedYAMLFile(name string) *CronJobSpecDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *CronJobSpecDie) DieFeedRawExtension(raw runtime.RawExtension) *CronJobSpecDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *CronJobSpecDie) DieRelease() batchv1.CronJobSpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *CronJobSpecDie) DieReleasePtr() *batchv1.CronJobSpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *CronJobSpecDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *CronJobSpecDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *CronJobSpecDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *CronJobSpecDie) DieStamp(fn func(r *batchv1.CronJobSpec)) *CronJobSpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *CronJobSpecDie) DieStampAt(jp string, fn interface{}) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *CronJobSpecDie) DieWith(fn func(d *CronJobSpecDie)) *CronJobSpecDie {
	nd := CronJobSpecBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *CronJobSpecDie) DeepCopy() *CronJobSpecDie {
	r := *d.r.DeepCopy()
	return &CronJobSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// The schedule in Cron format, see https://en.wikipedia.org/wiki/Cron.
func (d *CronJobSpecDie) Schedule(v string) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.Schedule = v
	})
}

// The time zone name for the given schedule, see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones. If not specified, this will default to the time zone of the kube-controller-manager process. The set of valid time zone names and the time zone offset is loaded from the system-wide time zone database by the API server during CronJob validation and the controller manager during execution. If no system-wide time zone database can be found a bundled version of the database is used instead. If the time zone name becomes invalid during the lifetime of a CronJob or due to a change in host configuration, the controller will stop creating new new Jobs and will create a system event with the reason UnknownTimeZone. More information can be found in https://kubernetes.io/docs/concepts/workloads/controllers/cron-jobs/#time-zones
func (d *CronJobSpecDie) TimeZone(v *string) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.TimeZone = v
	})
}

// Optional deadline in seconds for starting the job if it misses scheduled time for any reason.  Missed jobs executions will be counted as failed ones.
func (d *CronJobSpecDie) StartingDeadlineSeconds(v *int64) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.StartingDeadlineSeconds = v
	})
}

// Specifies how to treat concurrent executions of a Job. Valid values are:
//
// - "Allow" (default): allows CronJobs to run concurrently; - "Forbid": forbids concurrent runs, skipping next run if previous run hasn't finished yet; - "Replace": cancels currently running job and replaces it with a new one
func (d *CronJobSpecDie) ConcurrencyPolicy(v batchv1.ConcurrencyPolicy) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.ConcurrencyPolicy = v
	})
}

// This flag tells the controller to suspend subsequent executions, it does not apply to already started executions.  Defaults to false.
func (d *CronJobSpecDie) Suspend(v *bool) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.Suspend = v
	})
}

// Specifies the job that will be created when executing a CronJob.
func (d *CronJobSpecDie) JobTemplate(v batchv1.JobTemplateSpec) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.JobTemplate = v
	})
}

// The number of successful finished jobs to retain. Value must be non-negative integer. Defaults to 3.
func (d *CronJobSpecDie) SuccessfulJobsHistoryLimit(v *int32) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.SuccessfulJobsHistoryLimit = v
	})
}

// The number of failed finished jobs to retain. Value must be non-negative integer. Defaults to 1.
func (d *CronJobSpecDie) FailedJobsHistoryLimit(v *int32) *CronJobSpecDie {
	return d.DieStamp(func(r *batchv1.CronJobSpec) {
		r.FailedJobsHistoryLimit = v
	})
}

var CronJobStatusBlank = (&CronJobStatusDie{}).DieFeed(batchv1.CronJobStatus{})

type CronJobStatusDie struct {
	mutable bool
	r       batchv1.CronJobStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *CronJobStatusDie) DieImmutable(immutable bool) *CronJobStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *CronJobStatusDie) DieFeed(r batchv1.CronJobStatus) *CronJobStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &CronJobStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *CronJobStatusDie) DieFeedPtr(r *batchv1.CronJobStatus) *CronJobStatusDie {
	if r == nil {
		r = &batchv1.CronJobStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *CronJobStatusDie) DieFeedJSON(j []byte) *CronJobStatusDie {
	r := batchv1.CronJobStatus{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *CronJobStatusDie) DieFeedYAML(y []byte) *CronJobStatusDie {
	r := batchv1.CronJobStatus{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *CronJobStatusDie) DieFeedYAMLFile(name string) *CronJobStatusDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *CronJobStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *CronJobStatusDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *CronJobStatusDie) DieRelease() batchv1.CronJobStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *CronJobStatusDie) DieReleasePtr() *batchv1.CronJobStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *CronJobStatusDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *CronJobStatusDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *CronJobStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *CronJobStatusDie) DieStamp(fn func(r *batchv1.CronJobStatus)) *CronJobStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *CronJobStatusDie) DieStampAt(jp string, fn interface{}) *CronJobStatusDie {
	return d.DieStamp(func(r *batchv1.CronJobStatus) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *CronJobStatusDie) DieWith(fn func(d *CronJobStatusDie)) *CronJobStatusDie {
	nd := CronJobStatusBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *CronJobStatusDie) DeepCopy() *CronJobStatusDie {
	r := *d.r.DeepCopy()
	return &CronJobStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// A list of pointers to currently running jobs.
func (d *CronJobStatusDie) Active(v ...corev1.ObjectReference) *CronJobStatusDie {
	return d.DieStamp(func(r *batchv1.CronJobStatus) {
		r.Active = v
	})
}

// Information when was the last time the job was successfully scheduled.
func (d *CronJobStatusDie) LastScheduleTime(v *apismetav1.Time) *CronJobStatusDie {
	return d.DieStamp(func(r *batchv1.CronJobStatus) {
		r.LastScheduleTime = v
	})
}

// Information when was the last time the job successfully completed.
func (d *CronJobStatusDie) LastSuccessfulTime(v *apismetav1.Time) *CronJobStatusDie {
	return d.DieStamp(func(r *batchv1.CronJobStatus) {
		r.LastSuccessfulTime = v
	})
}

var JobBlank = (&JobDie{}).DieFeed(batchv1.Job{})

type JobDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       batchv1.Job
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *JobDie) DieImmutable(immutable bool) *JobDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *JobDie) DieFeed(r batchv1.Job) *JobDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &JobDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *JobDie) DieFeedPtr(r *batchv1.Job) *JobDie {
	if r == nil {
		r = &batchv1.Job{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *JobDie) DieFeedJSON(j []byte) *JobDie {
	r := batchv1.Job{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *JobDie) DieFeedYAML(y []byte) *JobDie {
	r := batchv1.Job{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *JobDie) DieFeedYAMLFile(name string) *JobDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *JobDie) DieFeedRawExtension(raw runtime.RawExtension) *JobDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *JobDie) DieRelease() batchv1.Job {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *JobDie) DieReleasePtr() *batchv1.Job {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *JobDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *JobDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *JobDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *JobDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *JobDie) DieStamp(fn func(r *batchv1.Job)) *JobDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *JobDie) DieStampAt(jp string, fn interface{}) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *JobDie) DieWith(fn func(d *JobDie)) *JobDie {
	nd := JobBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *JobDie) DeepCopy() *JobDie {
	r := *d.r.DeepCopy()
	return &JobDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*JobDie)(nil)

func (d *JobDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *JobDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *JobDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *JobDie) UnmarshalJSON(b []byte) error {
	if d == JobBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &batchv1.Job{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *JobDie) APIVersion(v string) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *JobDie) Kind(v string) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *JobDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// SpecDie stamps the resource's spec field with a mutable die.
func (d *JobDie) SpecDie(fn func(d *JobSpecDie)) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		d := JobSpecBlank.DieImmutable(false).DieFeed(r.Spec)
		fn(d)
		r.Spec = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *JobDie) StatusDie(fn func(d *JobStatusDie)) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		d := JobStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

// Specification of the desired behavior of a job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
func (d *JobDie) Spec(v batchv1.JobSpec) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		r.Spec = v
	})
}

// Current status of a job. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status
func (d *JobDie) Status(v batchv1.JobStatus) *JobDie {
	return d.DieStamp(func(r *batchv1.Job) {
		r.Status = v
	})
}

var JobSpecBlank = (&JobSpecDie{}).DieFeed(batchv1.JobSpec{})

type JobSpecDie struct {
	mutable bool
	r       batchv1.JobSpec
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *JobSpecDie) DieImmutable(immutable bool) *JobSpecDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *JobSpecDie) DieFeed(r batchv1.JobSpec) *JobSpecDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &JobSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *JobSpecDie) DieFeedPtr(r *batchv1.JobSpec) *JobSpecDie {
	if r == nil {
		r = &batchv1.JobSpec{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *JobSpecDie) DieFeedJSON(j []byte) *JobSpecDie {
	r := batchv1.JobSpec{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *JobSpecDie) DieFeedYAML(y []byte) *JobSpecDie {
	r := batchv1.JobSpec{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *JobSpecDie) DieFeedYAMLFile(name string) *JobSpecDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *JobSpecDie) DieFeedRawExtension(raw runtime.RawExtension) *JobSpecDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *JobSpecDie) DieRelease() batchv1.JobSpec {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *JobSpecDie) DieReleasePtr() *batchv1.JobSpec {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *JobSpecDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *JobSpecDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *JobSpecDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *JobSpecDie) DieStamp(fn func(r *batchv1.JobSpec)) *JobSpecDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *JobSpecDie) DieStampAt(jp string, fn interface{}) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *JobSpecDie) DieWith(fn func(d *JobSpecDie)) *JobSpecDie {
	nd := JobSpecBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *JobSpecDie) DeepCopy() *JobSpecDie {
	r := *d.r.DeepCopy()
	return &JobSpecDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
func (d *JobSpecDie) Parallelism(v *int32) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.Parallelism = v
	})
}

// Specifies the desired number of successfully finished pods the job should be run with.  Setting to null means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
func (d *JobSpecDie) Completions(v *int32) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.Completions = v
	})
}

// Specifies the duration in seconds relative to the startTime that the job may be continuously active before the system tries to terminate it; value must be positive integer. If a Job is suspended (at creation or through an update), this timer will effectively be stopped and reset when the Job is resumed again.
func (d *JobSpecDie) ActiveDeadlineSeconds(v *int64) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.ActiveDeadlineSeconds = v
	})
}

// Specifies the policy of handling failed pods. In particular, it allows to specify the set of actions and conditions which need to be satisfied to take the associated action. If empty, the default behaviour applies - the counter of failed pods, represented by the jobs's .status.failed field, is incremented and it is checked against the backoffLimit. This field cannot be used in combination with restartPolicy=OnFailure.
//
// This field is alpha-level. To use this field, you must enable the `JobPodFailurePolicy` feature gate (disabled by default).
func (d *JobSpecDie) PodFailurePolicy(v *batchv1.PodFailurePolicy) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.PodFailurePolicy = v
	})
}

// Specifies the number of retries before marking this job failed. Defaults to 6
func (d *JobSpecDie) BackoffLimit(v *int32) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.BackoffLimit = v
	})
}

// A label query over pods that should match the pod count. Normally, the system sets this field for you. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors
func (d *JobSpecDie) Selector(v *apismetav1.LabelSelector) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.Selector = v
	})
}

// manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector
func (d *JobSpecDie) ManualSelector(v *bool) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.ManualSelector = v
	})
}

// Describes the pod that will be created when executing a job. The only allowed template.spec.restartPolicy values are "Never" or "OnFailure". More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
func (d *JobSpecDie) Template(v corev1.PodTemplateSpec) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.Template = v
	})
}

// ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes, it is eligible to be automatically deleted. When the Job is being deleted, its lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset, the Job won't be automatically deleted. If this field is set to zero, the Job becomes eligible to be deleted immediately after it finishes.
func (d *JobSpecDie) TTLSecondsAfterFinished(v *int32) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.TTLSecondsAfterFinished = v
	})
}

// completionMode specifies how Pod completions are tracked. It can be `NonIndexed` (default) or `Indexed`.
//
// `NonIndexed` means that the Job is considered complete when there have been .spec.completions successfully completed Pods. Each Pod completion is homologous to each other.
//
// `Indexed` means that the Pods of a Job get an associated completion index from 0 to (.spec.completions - 1), available in the annotation batch.kubernetes.io/job-completion-index. The Job is considered complete when there is one successfully completed Pod for each index. When value is `Indexed`, .spec.completions must be specified and `.spec.parallelism` must be less than or equal to 10^5. In addition, The Pod name takes the form `$(job-name)-$(index)-$(random-string)`, the Pod hostname takes the form `$(job-name)-$(index)`.
//
// More completion modes can be added in the future. If the Job controller observes a mode that it doesn't recognize, which is possible during upgrades due to version skew, the controller skips updates for the Job.
func (d *JobSpecDie) CompletionMode(v *batchv1.CompletionMode) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.CompletionMode = v
	})
}

// suspend specifies whether the Job controller should create Pods or not. If a Job is created with suspend set to true, no Pods are created by the Job controller. If a Job is suspended after creation (i.e. the flag goes from false to true), the Job controller will delete all active Pods associated with this Job. Users must design their workload to gracefully handle this. Suspending a Job will reset the StartTime field of the Job, effectively resetting the ActiveDeadlineSeconds timer too. Defaults to false.
func (d *JobSpecDie) Suspend(v *bool) *JobSpecDie {
	return d.DieStamp(func(r *batchv1.JobSpec) {
		r.Suspend = v
	})
}

var PodFailurePolicyBlank = (&PodFailurePolicyDie{}).DieFeed(batchv1.PodFailurePolicy{})

type PodFailurePolicyDie struct {
	mutable bool
	r       batchv1.PodFailurePolicy
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodFailurePolicyDie) DieImmutable(immutable bool) *PodFailurePolicyDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodFailurePolicyDie) DieFeed(r batchv1.PodFailurePolicy) *PodFailurePolicyDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &PodFailurePolicyDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodFailurePolicyDie) DieFeedPtr(r *batchv1.PodFailurePolicy) *PodFailurePolicyDie {
	if r == nil {
		r = &batchv1.PodFailurePolicy{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodFailurePolicyDie) DieFeedJSON(j []byte) *PodFailurePolicyDie {
	r := batchv1.PodFailurePolicy{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodFailurePolicyDie) DieFeedYAML(y []byte) *PodFailurePolicyDie {
	r := batchv1.PodFailurePolicy{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodFailurePolicyDie) DieFeedYAMLFile(name string) *PodFailurePolicyDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyDie) DieFeedRawExtension(raw runtime.RawExtension) *PodFailurePolicyDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodFailurePolicyDie) DieRelease() batchv1.PodFailurePolicy {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodFailurePolicyDie) DieReleasePtr() *batchv1.PodFailurePolicy {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodFailurePolicyDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodFailurePolicyDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodFailurePolicyDie) DieStamp(fn func(r *batchv1.PodFailurePolicy)) *PodFailurePolicyDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodFailurePolicyDie) DieStampAt(jp string, fn interface{}) *PodFailurePolicyDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicy) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *PodFailurePolicyDie) DieWith(fn func(d *PodFailurePolicyDie)) *PodFailurePolicyDie {
	nd := PodFailurePolicyBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodFailurePolicyDie) DeepCopy() *PodFailurePolicyDie {
	r := *d.r.DeepCopy()
	return &PodFailurePolicyDie{
		mutable: d.mutable,
		r:       r,
	}
}

// A list of pod failure policy rules. The rules are evaluated in order. Once a rule matches a Pod failure, the remaining of the rules are ignored. When no rule matches the Pod failure, the default handling applies - the counter of pod failures is incremented and it is checked against the backoffLimit. At most 20 elements are allowed.
func (d *PodFailurePolicyDie) Rules(v ...batchv1.PodFailurePolicyRule) *PodFailurePolicyDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicy) {
		r.Rules = v
	})
}

var PodFailurePolicyRuleBlank = (&PodFailurePolicyRuleDie{}).DieFeed(batchv1.PodFailurePolicyRule{})

type PodFailurePolicyRuleDie struct {
	mutable bool
	r       batchv1.PodFailurePolicyRule
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodFailurePolicyRuleDie) DieImmutable(immutable bool) *PodFailurePolicyRuleDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodFailurePolicyRuleDie) DieFeed(r batchv1.PodFailurePolicyRule) *PodFailurePolicyRuleDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &PodFailurePolicyRuleDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodFailurePolicyRuleDie) DieFeedPtr(r *batchv1.PodFailurePolicyRule) *PodFailurePolicyRuleDie {
	if r == nil {
		r = &batchv1.PodFailurePolicyRule{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodFailurePolicyRuleDie) DieFeedJSON(j []byte) *PodFailurePolicyRuleDie {
	r := batchv1.PodFailurePolicyRule{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodFailurePolicyRuleDie) DieFeedYAML(y []byte) *PodFailurePolicyRuleDie {
	r := batchv1.PodFailurePolicyRule{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodFailurePolicyRuleDie) DieFeedYAMLFile(name string) *PodFailurePolicyRuleDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyRuleDie) DieFeedRawExtension(raw runtime.RawExtension) *PodFailurePolicyRuleDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodFailurePolicyRuleDie) DieRelease() batchv1.PodFailurePolicyRule {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodFailurePolicyRuleDie) DieReleasePtr() *batchv1.PodFailurePolicyRule {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodFailurePolicyRuleDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodFailurePolicyRuleDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyRuleDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodFailurePolicyRuleDie) DieStamp(fn func(r *batchv1.PodFailurePolicyRule)) *PodFailurePolicyRuleDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodFailurePolicyRuleDie) DieStampAt(jp string, fn interface{}) *PodFailurePolicyRuleDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyRule) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *PodFailurePolicyRuleDie) DieWith(fn func(d *PodFailurePolicyRuleDie)) *PodFailurePolicyRuleDie {
	nd := PodFailurePolicyRuleBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodFailurePolicyRuleDie) DeepCopy() *PodFailurePolicyRuleDie {
	r := *d.r.DeepCopy()
	return &PodFailurePolicyRuleDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Specifies the action taken on a pod failure when the requirements are satisfied. Possible values are:
//
// - FailJob: indicates that the pod's job is marked as Failed and all running pods are terminated. - Ignore: indicates that the counter towards the .backoffLimit is not incremented and a replacement pod is created. - Count: indicates that the pod is handled in the default way - the counter towards the .backoffLimit is incremented. Additional values are considered to be added in the future. Clients should react to an unknown action by skipping the rule.
func (d *PodFailurePolicyRuleDie) Action(v batchv1.PodFailurePolicyAction) *PodFailurePolicyRuleDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyRule) {
		r.Action = v
	})
}

// Represents the requirement on the container exit codes.
func (d *PodFailurePolicyRuleDie) OnExitCodes(v *batchv1.PodFailurePolicyOnExitCodesRequirement) *PodFailurePolicyRuleDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyRule) {
		r.OnExitCodes = v
	})
}

// Represents the requirement on the pod conditions. The requirement is represented as a list of pod condition patterns. The requirement is satisfied if at least one pattern matches an actual pod condition. At most 20 elements are allowed.
func (d *PodFailurePolicyRuleDie) OnPodConditions(v ...batchv1.PodFailurePolicyOnPodConditionsPattern) *PodFailurePolicyRuleDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyRule) {
		r.OnPodConditions = v
	})
}

var PodFailurePolicyOnExitCodesRequirementBlank = (&PodFailurePolicyOnExitCodesRequirementDie{}).DieFeed(batchv1.PodFailurePolicyOnExitCodesRequirement{})

type PodFailurePolicyOnExitCodesRequirementDie struct {
	mutable bool
	r       batchv1.PodFailurePolicyOnExitCodesRequirement
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieImmutable(immutable bool) *PodFailurePolicyOnExitCodesRequirementDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieFeed(r batchv1.PodFailurePolicyOnExitCodesRequirement) *PodFailurePolicyOnExitCodesRequirementDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &PodFailurePolicyOnExitCodesRequirementDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieFeedPtr(r *batchv1.PodFailurePolicyOnExitCodesRequirement) *PodFailurePolicyOnExitCodesRequirementDie {
	if r == nil {
		r = &batchv1.PodFailurePolicyOnExitCodesRequirement{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieFeedJSON(j []byte) *PodFailurePolicyOnExitCodesRequirementDie {
	r := batchv1.PodFailurePolicyOnExitCodesRequirement{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieFeedYAML(y []byte) *PodFailurePolicyOnExitCodesRequirementDie {
	r := batchv1.PodFailurePolicyOnExitCodesRequirement{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieFeedYAMLFile(name string) *PodFailurePolicyOnExitCodesRequirementDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieFeedRawExtension(raw runtime.RawExtension) *PodFailurePolicyOnExitCodesRequirementDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieRelease() batchv1.PodFailurePolicyOnExitCodesRequirement {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieReleasePtr() *batchv1.PodFailurePolicyOnExitCodesRequirement {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieStamp(fn func(r *batchv1.PodFailurePolicyOnExitCodesRequirement)) *PodFailurePolicyOnExitCodesRequirementDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieStampAt(jp string, fn interface{}) *PodFailurePolicyOnExitCodesRequirementDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnExitCodesRequirement) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DieWith(fn func(d *PodFailurePolicyOnExitCodesRequirementDie)) *PodFailurePolicyOnExitCodesRequirementDie {
	nd := PodFailurePolicyOnExitCodesRequirementBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodFailurePolicyOnExitCodesRequirementDie) DeepCopy() *PodFailurePolicyOnExitCodesRequirementDie {
	r := *d.r.DeepCopy()
	return &PodFailurePolicyOnExitCodesRequirementDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Restricts the check for exit codes to the container with the specified name. When null, the rule applies to all containers. When specified, it should match one the container or initContainer names in the pod template.
func (d *PodFailurePolicyOnExitCodesRequirementDie) ContainerName(v *string) *PodFailurePolicyOnExitCodesRequirementDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnExitCodesRequirement) {
		r.ContainerName = v
	})
}

// Represents the relationship between the container exit code(s) and the specified values. Containers completed with success (exit code 0) are excluded from the requirement check. Possible values are:
//
// - In: the requirement is satisfied if at least one container exit code (might be multiple if there are multiple containers not restricted by the 'containerName' field) is in the set of specified values. - NotIn: the requirement is satisfied if at least one container exit code (might be multiple if there are multiple containers not restricted by the 'containerName' field) is not in the set of specified values. Additional values are considered to be added in the future. Clients should react to an unknown operator by assuming the requirement is not satisfied.
func (d *PodFailurePolicyOnExitCodesRequirementDie) Operator(v batchv1.PodFailurePolicyOnExitCodesOperator) *PodFailurePolicyOnExitCodesRequirementDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnExitCodesRequirement) {
		r.Operator = v
	})
}

// Specifies the set of values. Each returned container exit code (might be multiple in case of multiple containers) is checked against this set of values with respect to the operator. The list of values must be ordered and must not contain duplicates. Value '0' cannot be used for the In operator. At least one element is required. At most 255 elements are allowed.
func (d *PodFailurePolicyOnExitCodesRequirementDie) Values(v ...int32) *PodFailurePolicyOnExitCodesRequirementDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnExitCodesRequirement) {
		r.Values = v
	})
}

var PodFailurePolicyOnPodConditionsPatternBlank = (&PodFailurePolicyOnPodConditionsPatternDie{}).DieFeed(batchv1.PodFailurePolicyOnPodConditionsPattern{})

type PodFailurePolicyOnPodConditionsPatternDie struct {
	mutable bool
	r       batchv1.PodFailurePolicyOnPodConditionsPattern
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieImmutable(immutable bool) *PodFailurePolicyOnPodConditionsPatternDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieFeed(r batchv1.PodFailurePolicyOnPodConditionsPattern) *PodFailurePolicyOnPodConditionsPatternDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &PodFailurePolicyOnPodConditionsPatternDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieFeedPtr(r *batchv1.PodFailurePolicyOnPodConditionsPattern) *PodFailurePolicyOnPodConditionsPatternDie {
	if r == nil {
		r = &batchv1.PodFailurePolicyOnPodConditionsPattern{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieFeedJSON(j []byte) *PodFailurePolicyOnPodConditionsPatternDie {
	r := batchv1.PodFailurePolicyOnPodConditionsPattern{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieFeedYAML(y []byte) *PodFailurePolicyOnPodConditionsPatternDie {
	r := batchv1.PodFailurePolicyOnPodConditionsPattern{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieFeedYAMLFile(name string) *PodFailurePolicyOnPodConditionsPatternDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieFeedRawExtension(raw runtime.RawExtension) *PodFailurePolicyOnPodConditionsPatternDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieRelease() batchv1.PodFailurePolicyOnPodConditionsPattern {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieReleasePtr() *batchv1.PodFailurePolicyOnPodConditionsPattern {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieStamp(fn func(r *batchv1.PodFailurePolicyOnPodConditionsPattern)) *PodFailurePolicyOnPodConditionsPatternDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieStampAt(jp string, fn interface{}) *PodFailurePolicyOnPodConditionsPatternDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnPodConditionsPattern) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DieWith(fn func(d *PodFailurePolicyOnPodConditionsPatternDie)) *PodFailurePolicyOnPodConditionsPatternDie {
	nd := PodFailurePolicyOnPodConditionsPatternBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *PodFailurePolicyOnPodConditionsPatternDie) DeepCopy() *PodFailurePolicyOnPodConditionsPatternDie {
	r := *d.r.DeepCopy()
	return &PodFailurePolicyOnPodConditionsPatternDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Specifies the required Pod condition type. To match a pod condition it is required that specified type equals the pod condition type.
func (d *PodFailurePolicyOnPodConditionsPatternDie) Type(v corev1.PodConditionType) *PodFailurePolicyOnPodConditionsPatternDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnPodConditionsPattern) {
		r.Type = v
	})
}

// Specifies the required Pod condition status. To match a pod condition it is required that the specified status equals the pod condition status. Defaults to True.
func (d *PodFailurePolicyOnPodConditionsPatternDie) Status(v corev1.ConditionStatus) *PodFailurePolicyOnPodConditionsPatternDie {
	return d.DieStamp(func(r *batchv1.PodFailurePolicyOnPodConditionsPattern) {
		r.Status = v
	})
}

var JobStatusBlank = (&JobStatusDie{}).DieFeed(batchv1.JobStatus{})

type JobStatusDie struct {
	mutable bool
	r       batchv1.JobStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *JobStatusDie) DieImmutable(immutable bool) *JobStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *JobStatusDie) DieFeed(r batchv1.JobStatus) *JobStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &JobStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *JobStatusDie) DieFeedPtr(r *batchv1.JobStatus) *JobStatusDie {
	if r == nil {
		r = &batchv1.JobStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *JobStatusDie) DieFeedJSON(j []byte) *JobStatusDie {
	r := batchv1.JobStatus{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *JobStatusDie) DieFeedYAML(y []byte) *JobStatusDie {
	r := batchv1.JobStatus{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *JobStatusDie) DieFeedYAMLFile(name string) *JobStatusDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *JobStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *JobStatusDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *JobStatusDie) DieRelease() batchv1.JobStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *JobStatusDie) DieReleasePtr() *batchv1.JobStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *JobStatusDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *JobStatusDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *JobStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *JobStatusDie) DieStamp(fn func(r *batchv1.JobStatus)) *JobStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *JobStatusDie) DieStampAt(jp string, fn interface{}) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *JobStatusDie) DieWith(fn func(d *JobStatusDie)) *JobStatusDie {
	nd := JobStatusBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *JobStatusDie) DeepCopy() *JobStatusDie {
	r := *d.r.DeepCopy()
	return &JobStatusDie{
		mutable: d.mutable,
		r:       r,
	}
}

// The latest available observations of an object's current state. When a Job fails, one of the conditions will have type "Failed" and status true. When a Job is suspended, one of the conditions will have type "Suspended" and status true; when the Job is resumed, the status of this condition will become false. When a Job is completed, one of the conditions will have type "Complete" and status true. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/
func (d *JobStatusDie) Conditions(v ...batchv1.JobCondition) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.Conditions = v
	})
}

// Represents time when the job controller started processing a job. When a Job is created in the suspended state, this field is not set until the first time it is resumed. This field is reset every time a Job is resumed from suspension. It is represented in RFC3339 form and is in UTC.
func (d *JobStatusDie) StartTime(v *apismetav1.Time) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.StartTime = v
	})
}

// Represents time when the job was completed. It is not guaranteed to be set in happens-before order across separate operations. It is represented in RFC3339 form and is in UTC. The completion time is only set when the job finishes successfully.
func (d *JobStatusDie) CompletionTime(v *apismetav1.Time) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.CompletionTime = v
	})
}

// The number of pending and running pods.
func (d *JobStatusDie) Active(v int32) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.Active = v
	})
}

// The number of pods which reached phase Succeeded.
func (d *JobStatusDie) Succeeded(v int32) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.Succeeded = v
	})
}

// The number of pods which reached phase Failed.
func (d *JobStatusDie) Failed(v int32) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.Failed = v
	})
}

// completedIndexes holds the completed indexes when .spec.completionMode = "Indexed" in a text format. The indexes are represented as decimal integers separated by commas. The numbers are listed in increasing order. Three or more consecutive numbers are compressed and represented by the first and last element of the series, separated by a hyphen. For example, if the completed indexes are 1, 3, 4, 5 and 7, they are represented as "1,3-5,7".
func (d *JobStatusDie) CompletedIndexes(v string) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.CompletedIndexes = v
	})
}

// uncountedTerminatedPods holds the UIDs of Pods that have terminated but the job controller hasn't yet accounted for in the status counters.
//
// The job controller creates pods with a finalizer. When a pod terminates (succeeded or failed), the controller does three steps to account for it in the job status:
//
// 1. Add the pod UID to the arrays in this field. 2. Remove the pod finalizer. 3. Remove the pod UID from the arrays while increasing the corresponding counter.
//
// Old jobs might not be tracked using this field, in which case the field remains null.
func (d *JobStatusDie) UncountedTerminatedPods(v *batchv1.UncountedTerminatedPods) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.UncountedTerminatedPods = v
	})
}

// The number of pods which have a Ready condition.
//
// This field is beta-level. The job controller populates the field when the feature gate JobReadyPods is enabled (enabled by default).
func (d *JobStatusDie) Ready(v *int32) *JobStatusDie {
	return d.DieStamp(func(r *batchv1.JobStatus) {
		r.Ready = v
	})
}

var UncountedTerminatedPodsBlank = (&UncountedTerminatedPodsDie{}).DieFeed(batchv1.UncountedTerminatedPods{})

type UncountedTerminatedPodsDie struct {
	mutable bool
	r       batchv1.UncountedTerminatedPods
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *UncountedTerminatedPodsDie) DieImmutable(immutable bool) *UncountedTerminatedPodsDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *UncountedTerminatedPodsDie) DieFeed(r batchv1.UncountedTerminatedPods) *UncountedTerminatedPodsDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &UncountedTerminatedPodsDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *UncountedTerminatedPodsDie) DieFeedPtr(r *batchv1.UncountedTerminatedPods) *UncountedTerminatedPodsDie {
	if r == nil {
		r = &batchv1.UncountedTerminatedPods{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *UncountedTerminatedPodsDie) DieFeedJSON(j []byte) *UncountedTerminatedPodsDie {
	r := batchv1.UncountedTerminatedPods{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *UncountedTerminatedPodsDie) DieFeedYAML(y []byte) *UncountedTerminatedPodsDie {
	r := batchv1.UncountedTerminatedPods{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *UncountedTerminatedPodsDie) DieFeedYAMLFile(name string) *UncountedTerminatedPodsDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *UncountedTerminatedPodsDie) DieFeedRawExtension(raw runtime.RawExtension) *UncountedTerminatedPodsDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *UncountedTerminatedPodsDie) DieRelease() batchv1.UncountedTerminatedPods {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *UncountedTerminatedPodsDie) DieReleasePtr() *batchv1.UncountedTerminatedPods {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *UncountedTerminatedPodsDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *UncountedTerminatedPodsDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *UncountedTerminatedPodsDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *UncountedTerminatedPodsDie) DieStamp(fn func(r *batchv1.UncountedTerminatedPods)) *UncountedTerminatedPodsDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *UncountedTerminatedPodsDie) DieStampAt(jp string, fn interface{}) *UncountedTerminatedPodsDie {
	return d.DieStamp(func(r *batchv1.UncountedTerminatedPods) {
		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			args := []reflectx.Value{cv}
			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *UncountedTerminatedPodsDie) DieWith(fn func(d *UncountedTerminatedPodsDie)) *UncountedTerminatedPodsDie {
	nd := UncountedTerminatedPodsBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	fn(nd)
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *UncountedTerminatedPodsDie) DeepCopy() *UncountedTerminatedPodsDie {
	r := *d.r.DeepCopy()
	return &UncountedTerminatedPodsDie{
		mutable: d.mutable,
		r:       r,
	}
}

// succeeded holds UIDs of succeeded Pods.
func (d *UncountedTerminatedPodsDie) Succeeded(v ...types.UID) *UncountedTerminatedPodsDie {
	return d.DieStamp(func(r *batchv1.UncountedTerminatedPods) {
		r.Succeeded = v
	})
}

// failed holds UIDs of failed Pods.
func (d *UncountedTerminatedPodsDie) Failed(v ...types.UID) *UncountedTerminatedPodsDie {
	return d.DieStamp(func(r *batchv1.UncountedTerminatedPods) {
		r.Failed = v
	})
}
