//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021-2022 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1alpha3

import (
	testing "reconciler.io/dies/testing"
	testingx "testing"
)

func TestPodGroupDie_MissingMethods(t *testingx.T) {
	die := PodGroupBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupDie: %s", diff.List())
	}
}

func TestPodGroupSpecDie_MissingMethods(t *testingx.T) {
	die := PodGroupSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupSpecDie: %s", diff.List())
	}
}

func TestWorkloadReferenceDie_MissingMethods(t *testingx.T) {
	die := WorkloadReferenceBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadReferenceDie: %s", diff.List())
	}
}

func TestPodGroupSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := PodGroupSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupSchedulingPolicyDie: %s", diff.List())
	}
}

func TestBasicSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := BasicSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for BasicSchedulingPolicyDie: %s", diff.List())
	}
}

func TestGangSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := GangSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for GangSchedulingPolicyDie: %s", diff.List())
	}
}

func TestPodGroupSchedulingConstraintsDie_MissingMethods(t *testingx.T) {
	die := PodGroupSchedulingConstraintsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupSchedulingConstraintsDie: %s", diff.List())
	}
}

func TestTopologyConstraintDie_MissingMethods(t *testingx.T) {
	die := TopologyConstraintBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for TopologyConstraintDie: %s", diff.List())
	}
}

func TestPodGroupResourceClaimDie_MissingMethods(t *testingx.T) {
	die := PodGroupResourceClaimBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupResourceClaimDie: %s", diff.List())
	}
}

func TestDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := DisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for DisruptionModeDie: %s", diff.List())
	}
}

func TestSingleDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := SingleDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SingleDisruptionModeDie: %s", diff.List())
	}
}

func TestAllDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := AllDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for AllDisruptionModeDie: %s", diff.List())
	}
}

func TestPodGroupStatusDie_MissingMethods(t *testingx.T) {
	die := PodGroupStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupStatusDie: %s", diff.List())
	}
}

func TestPodGroupResourceClaimStatusDie_MissingMethods(t *testingx.T) {
	die := PodGroupResourceClaimStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupResourceClaimStatusDie: %s", diff.List())
	}
}

func TestWorkloadDie_MissingMethods(t *testingx.T) {
	die := WorkloadBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadDie: %s", diff.List())
	}
}

func TestWorkloadSpecDie_MissingMethods(t *testingx.T) {
	die := WorkloadSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadSpecDie: %s", diff.List())
	}
}

func TestTypedLocalObjectReferenceDie_MissingMethods(t *testingx.T) {
	die := TypedLocalObjectReferenceBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for TypedLocalObjectReferenceDie: %s", diff.List())
	}
}

func TestPodGroupTemplateDie_MissingMethods(t *testingx.T) {
	die := PodGroupTemplateBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for PodGroupTemplateDie: %s", diff.List())
	}
}

func TestCompositePodGroupTemplateDie_MissingMethods(t *testingx.T) {
	die := CompositePodGroupTemplateBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for CompositePodGroupTemplateDie: %s", diff.List())
	}
}

func TestCompositePodGroupSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := CompositePodGroupSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for CompositePodGroupSchedulingPolicyDie: %s", diff.List())
	}
}

func TestCompositeBasicSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := CompositeBasicSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for CompositeBasicSchedulingPolicyDie: %s", diff.List())
	}
}

func TestCompositeGangSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := CompositeGangSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for CompositeGangSchedulingPolicyDie: %s", diff.List())
	}
}

func TestCompositePodGroupSchedulingConstraintsDie_MissingMethods(t *testingx.T) {
	die := CompositePodGroupSchedulingConstraintsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for CompositePodGroupSchedulingConstraintsDie: %s", diff.List())
	}
}

func TestCompositeDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := CompositeDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for CompositeDisruptionModeDie: %s", diff.List())
	}
}

func TestSingleCompositeDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := SingleCompositeDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SingleCompositeDisruptionModeDie: %s", diff.List())
	}
}

func TestAllCompositeDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := AllCompositeDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for AllCompositeDisruptionModeDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupSchedulingPolicyDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupBasicSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupBasicSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupBasicSchedulingPolicyDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupGangSchedulingPolicyDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupGangSchedulingPolicyBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupGangSchedulingPolicyDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupSchedulingConstraintsDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupSchedulingConstraintsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupSchedulingConstraintsDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupDisruptionModeDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupSingleDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupSingleDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupSingleDisruptionModeDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupAllDisruptionModeDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupAllDisruptionModeBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupAllDisruptionModeDie: %s", diff.List())
	}
}

func TestWorkloadPodGroupResourceClaimDie_MissingMethods(t *testingx.T) {
	die := WorkloadPodGroupResourceClaimBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WorkloadPodGroupResourceClaimDie: %s", diff.List())
	}
}
