//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	fmtx "fmt"
	metav1 "github.com/scothis/dies/apis/meta/v1"
	rbacv1 "k8s.io/api/rbac/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
)

var (
	GroupVersion  = schema.GroupVersion{Group: "rbac.authorization.k8s.io", Version: "v1"}
	SchemeBuilder = runtime.NewSchemeBuilder()
	AddToScheme   = SchemeBuilder.AddToScheme
)

type ClusterRoleDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       rbacv1.ClusterRole
}

var ClusterRoleBlank = (&ClusterRoleDie{}).DieFeed(rbacv1.ClusterRole{})

func (d *ClusterRoleDie) DieImmutable(immutable bool) *ClusterRoleDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

func (d *ClusterRoleDie) DieFeed(r rbacv1.ClusterRole) *ClusterRoleDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ClusterRoleDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *ClusterRoleDie) DieRelease() rbacv1.ClusterRole {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

func (d *ClusterRoleDie) DieStamp(fn func(r *rbacv1.ClusterRole)) *ClusterRoleDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

func (d *ClusterRoleDie) DeepCopy() *ClusterRoleDie {
	r := *d.r.DeepCopy()
	return &ClusterRoleDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *ClusterRoleDie) DeepCopyObject() runtime.Object {
	return d.DeepCopy()
}

func (d *ClusterRoleDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ClusterRoleDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ClusterRoleDie) UnmarshalJSON(b []byte) error {
	if d == ClusterRoleBlank {
		return fmtx.Errorf("cannot unmarshing into the root object, create a copy first")
	}
	r := &rbacv1.ClusterRole{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

func (d *ClusterRoleDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *ClusterRoleDie {
	return d.DieStamp(func(r *rbacv1.ClusterRole) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

var _ apismetav1.Object = (*ClusterRoleDie)(nil)
var _ apismetav1.ObjectMetaAccessor = (*ClusterRoleDie)(nil)
var _ runtime.Object = (*ClusterRoleDie)(nil)

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(GroupVersion.WithKind("ClusterRole"), &ClusterRoleDie{})
		return nil
	})
}

func (d *ClusterRoleDie) AggregationRule(v *rbacv1.AggregationRule) *ClusterRoleDie {
	return d.DieStamp(func(r *rbacv1.ClusterRole) {
		r.AggregationRule = v
	})
}

func (d *ClusterRoleDie) Rules(v ...rbacv1.PolicyRule) *ClusterRoleDie {
	return d.DieStamp(func(r *rbacv1.ClusterRole) {
		r.Rules = v
	})
}

type ClusterRoleBindingDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       rbacv1.ClusterRoleBinding
}

var ClusterRoleBindingBlank = (&ClusterRoleBindingDie{}).DieFeed(rbacv1.ClusterRoleBinding{})

func (d *ClusterRoleBindingDie) DieImmutable(immutable bool) *ClusterRoleBindingDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

func (d *ClusterRoleBindingDie) DieFeed(r rbacv1.ClusterRoleBinding) *ClusterRoleBindingDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ClusterRoleBindingDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *ClusterRoleBindingDie) DieRelease() rbacv1.ClusterRoleBinding {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

func (d *ClusterRoleBindingDie) DieStamp(fn func(r *rbacv1.ClusterRoleBinding)) *ClusterRoleBindingDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

func (d *ClusterRoleBindingDie) DeepCopy() *ClusterRoleBindingDie {
	r := *d.r.DeepCopy()
	return &ClusterRoleBindingDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *ClusterRoleBindingDie) DeepCopyObject() runtime.Object {
	return d.DeepCopy()
}

func (d *ClusterRoleBindingDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ClusterRoleBindingDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ClusterRoleBindingDie) UnmarshalJSON(b []byte) error {
	if d == ClusterRoleBindingBlank {
		return fmtx.Errorf("cannot unmarshing into the root object, create a copy first")
	}
	r := &rbacv1.ClusterRoleBinding{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

func (d *ClusterRoleBindingDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *ClusterRoleBindingDie {
	return d.DieStamp(func(r *rbacv1.ClusterRoleBinding) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

var _ apismetav1.Object = (*ClusterRoleBindingDie)(nil)
var _ apismetav1.ObjectMetaAccessor = (*ClusterRoleBindingDie)(nil)
var _ runtime.Object = (*ClusterRoleBindingDie)(nil)

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(GroupVersion.WithKind("ClusterRoleBinding"), &ClusterRoleBindingDie{})
		return nil
	})
}

func (d *ClusterRoleBindingDie) Subjects(v ...rbacv1.Subject) *ClusterRoleBindingDie {
	return d.DieStamp(func(r *rbacv1.ClusterRoleBinding) {
		r.Subjects = v
	})
}

func (d *ClusterRoleBindingDie) RoleRef(v rbacv1.RoleRef) *ClusterRoleBindingDie {
	return d.DieStamp(func(r *rbacv1.ClusterRoleBinding) {
		r.RoleRef = v
	})
}

type RoleDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       rbacv1.Role
}

var RoleBlank = (&RoleDie{}).DieFeed(rbacv1.Role{})

func (d *RoleDie) DieImmutable(immutable bool) *RoleDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

func (d *RoleDie) DieFeed(r rbacv1.Role) *RoleDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &RoleDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *RoleDie) DieRelease() rbacv1.Role {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

func (d *RoleDie) DieStamp(fn func(r *rbacv1.Role)) *RoleDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

func (d *RoleDie) DeepCopy() *RoleDie {
	r := *d.r.DeepCopy()
	return &RoleDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *RoleDie) DeepCopyObject() runtime.Object {
	return d.DeepCopy()
}

func (d *RoleDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *RoleDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *RoleDie) UnmarshalJSON(b []byte) error {
	if d == RoleBlank {
		return fmtx.Errorf("cannot unmarshing into the root object, create a copy first")
	}
	r := &rbacv1.Role{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

func (d *RoleDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *RoleDie {
	return d.DieStamp(func(r *rbacv1.Role) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

var _ apismetav1.Object = (*RoleDie)(nil)
var _ apismetav1.ObjectMetaAccessor = (*RoleDie)(nil)
var _ runtime.Object = (*RoleDie)(nil)

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(GroupVersion.WithKind("Role"), &RoleDie{})
		return nil
	})
}

func (d *RoleDie) Rules(v ...rbacv1.PolicyRule) *RoleDie {
	return d.DieStamp(func(r *rbacv1.Role) {
		r.Rules = v
	})
}

type RoleBindingDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       rbacv1.RoleBinding
}

var RoleBindingBlank = (&RoleBindingDie{}).DieFeed(rbacv1.RoleBinding{})

func (d *RoleBindingDie) DieImmutable(immutable bool) *RoleBindingDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

func (d *RoleBindingDie) DieFeed(r rbacv1.RoleBinding) *RoleBindingDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &RoleBindingDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *RoleBindingDie) DieRelease() rbacv1.RoleBinding {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

func (d *RoleBindingDie) DieStamp(fn func(r *rbacv1.RoleBinding)) *RoleBindingDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

func (d *RoleBindingDie) DeepCopy() *RoleBindingDie {
	r := *d.r.DeepCopy()
	return &RoleBindingDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

func (d *RoleBindingDie) DeepCopyObject() runtime.Object {
	return d.DeepCopy()
}

func (d *RoleBindingDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *RoleBindingDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *RoleBindingDie) UnmarshalJSON(b []byte) error {
	if d == RoleBindingBlank {
		return fmtx.Errorf("cannot unmarshing into the root object, create a copy first")
	}
	r := &rbacv1.RoleBinding{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

func (d *RoleBindingDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *RoleBindingDie {
	return d.DieStamp(func(r *rbacv1.RoleBinding) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

var _ apismetav1.Object = (*RoleBindingDie)(nil)
var _ apismetav1.ObjectMetaAccessor = (*RoleBindingDie)(nil)
var _ runtime.Object = (*RoleBindingDie)(nil)

func init() {
	SchemeBuilder.Register(func(s *runtime.Scheme) error {
		s.AddKnownTypeWithName(GroupVersion.WithKind("RoleBinding"), &RoleBindingDie{})
		return nil
	})
}

func (d *RoleBindingDie) Subjects(v ...rbacv1.Subject) *RoleBindingDie {
	return d.DieStamp(func(r *rbacv1.RoleBinding) {
		r.Subjects = v
	})
}

func (d *RoleBindingDie) RoleRef(v rbacv1.RoleRef) *RoleBindingDie {
	return d.DieStamp(func(r *rbacv1.RoleBinding) {
		r.RoleRef = v
	})
}
