//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/types"
)

type ConditionDie struct {
	mutable bool
	r       metav1.Condition
}

var ConditionBlank = (&ConditionDie{}).DieFeed(metav1.Condition{})

func (d *ConditionDie) DieImmutable(immutable bool) *ConditionDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

func (d *ConditionDie) DieFeed(r metav1.Condition) *ConditionDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ConditionDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *ConditionDie) DieRelease() metav1.Condition {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

func (d *ConditionDie) DieStamp(fn func(r *metav1.Condition)) *ConditionDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

func (d *ConditionDie) DeepCopy() *ConditionDie {
	r := *d.r.DeepCopy()
	return &ConditionDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *ConditionDie) Type(v string) *ConditionDie {
	return d.DieStamp(func(r *metav1.Condition) {
		r.Type = v
	})
}

func (d *ConditionDie) Status(v metav1.ConditionStatus) *ConditionDie {
	return d.DieStamp(func(r *metav1.Condition) {
		r.Status = v
	})
}

func (d *ConditionDie) ObservedGeneration(v int64) *ConditionDie {
	return d.DieStamp(func(r *metav1.Condition) {
		r.ObservedGeneration = v
	})
}

func (d *ConditionDie) LastTransitionTime(v metav1.Time) *ConditionDie {
	return d.DieStamp(func(r *metav1.Condition) {
		r.LastTransitionTime = v
	})
}

func (d *ConditionDie) Reason(v string) *ConditionDie {
	return d.DieStamp(func(r *metav1.Condition) {
		r.Reason = v
	})
}

func (d *ConditionDie) Message(v string) *ConditionDie {
	return d.DieStamp(func(r *metav1.Condition) {
		r.Message = v
	})
}

type ObjectMetaDie struct {
	mutable bool
	r       metav1.ObjectMeta
}

var ObjectMetaBlank = (&ObjectMetaDie{}).DieFeed(metav1.ObjectMeta{})

func (d *ObjectMetaDie) DieImmutable(immutable bool) *ObjectMetaDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

func (d *ObjectMetaDie) DieFeed(r metav1.ObjectMeta) *ObjectMetaDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ObjectMetaDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *ObjectMetaDie) DieRelease() metav1.ObjectMeta {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

func (d *ObjectMetaDie) DieStamp(fn func(r *metav1.ObjectMeta)) *ObjectMetaDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

func (d *ObjectMetaDie) DeepCopy() *ObjectMetaDie {
	r := *d.r.DeepCopy()
	return &ObjectMetaDie{
		mutable: d.mutable,
		r:       r,
	}
}

func (d *ObjectMetaDie) Name(v string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.Name = v
	})
}

func (d *ObjectMetaDie) GenerateName(v string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.GenerateName = v
	})
}

func (d *ObjectMetaDie) Namespace(v string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.Namespace = v
	})
}

func (d *ObjectMetaDie) SelfLink(v string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.SelfLink = v
	})
}

func (d *ObjectMetaDie) UID(v types.UID) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.UID = v
	})
}

func (d *ObjectMetaDie) ResourceVersion(v string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.ResourceVersion = v
	})
}

func (d *ObjectMetaDie) Generation(v int64) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.Generation = v
	})
}

func (d *ObjectMetaDie) CreationTimestamp(v metav1.Time) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.CreationTimestamp = v
	})
}

func (d *ObjectMetaDie) DeletionTimestamp(v *metav1.Time) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.DeletionTimestamp = v
	})
}

func (d *ObjectMetaDie) DeletionGracePeriodSeconds(v *int64) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.DeletionGracePeriodSeconds = v
	})
}

func (d *ObjectMetaDie) Labels(v map[string]string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.Labels = v
	})
}

func (d *ObjectMetaDie) Annotations(v map[string]string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.Annotations = v
	})
}

func (d *ObjectMetaDie) OwnerReferences(v ...metav1.OwnerReference) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.OwnerReferences = v
	})
}

func (d *ObjectMetaDie) Finalizers(v ...string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.Finalizers = v
	})
}

func (d *ObjectMetaDie) ClusterName(v string) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.ClusterName = v
	})
}

func (d *ObjectMetaDie) ManagedFields(v ...metav1.ManagedFieldsEntry) *ObjectMetaDie {
	return d.DieStamp(func(r *metav1.ObjectMeta) {
		r.ManagedFields = v
	})
}
