//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021-2022 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	testing "reconciler.io/dies/testing"
	testingx "testing"
)

func TestLocalSubjectAccessReviewDie_MissingMethods(t *testingx.T) {
	die := LocalSubjectAccessReviewBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for LocalSubjectAccessReviewDie: %s", diff.List())
	}
}

func TestSelfSubjectAccessReviewDie_MissingMethods(t *testingx.T) {
	die := SelfSubjectAccessReviewBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SelfSubjectAccessReviewDie: %s", diff.List())
	}
}

func TestSelfSubjectAccessReviewSpecDie_MissingMethods(t *testingx.T) {
	die := SelfSubjectAccessReviewSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SelfSubjectAccessReviewSpecDie: %s", diff.List())
	}
}

func TestSelfSubjectRulesReviewDie_MissingMethods(t *testingx.T) {
	die := SelfSubjectRulesReviewBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SelfSubjectRulesReviewDie: %s", diff.List())
	}
}

func TestSelfSubjectRulesReviewSpecDie_MissingMethods(t *testingx.T) {
	die := SelfSubjectRulesReviewSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SelfSubjectRulesReviewSpecDie: %s", diff.List())
	}
}

func TestSubjectRulesReviewStatusDie_MissingMethods(t *testingx.T) {
	die := SubjectRulesReviewStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SubjectRulesReviewStatusDie: %s", diff.List())
	}
}

func TestResourceRuleDie_MissingMethods(t *testingx.T) {
	die := ResourceRuleBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ResourceRuleDie: %s", diff.List())
	}
}

func TestNonResourceRuleDie_MissingMethods(t *testingx.T) {
	die := NonResourceRuleBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for NonResourceRuleDie: %s", diff.List())
	}
}

func TestSubjectAccessReviewDie_MissingMethods(t *testingx.T) {
	die := SubjectAccessReviewBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SubjectAccessReviewDie: %s", diff.List())
	}
}

func TestSubjectAccessReviewSpecDie_MissingMethods(t *testingx.T) {
	die := SubjectAccessReviewSpecBlank
	ignore := []string{"Extra"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SubjectAccessReviewSpecDie: %s", diff.List())
	}
}

func TestResourceAttributesDie_MissingMethods(t *testingx.T) {
	die := ResourceAttributesBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ResourceAttributesDie: %s", diff.List())
	}
}

func TestNonResourceAttributesDie_MissingMethods(t *testingx.T) {
	die := NonResourceAttributesBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for NonResourceAttributesDie: %s", diff.List())
	}
}

func TestSubjectAccessReviewStatusDie_MissingMethods(t *testingx.T) {
	die := SubjectAccessReviewStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for SubjectAccessReviewStatusDie: %s", diff.List())
	}
}
