//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021-2022 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	json "encoding/json"
	fmtx "fmt"
	admissionregistrationv1 "k8s.io/api/admissionregistration/v1"
	apismetav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	jsonpath "k8s.io/client-go/util/jsonpath"
	osx "os"
	metav1 "reconciler.io/dies/apis/meta/v1"
	reflectx "reflect"
	yaml "sigs.k8s.io/yaml"
)

var WebhookClientConfigBlank = (&WebhookClientConfigDie{}).DieFeed(admissionregistrationv1.WebhookClientConfig{})

type WebhookClientConfigDie struct {
	mutable bool
	r       admissionregistrationv1.WebhookClientConfig
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *WebhookClientConfigDie) DieImmutable(immutable bool) *WebhookClientConfigDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *WebhookClientConfigDie) DieFeed(r admissionregistrationv1.WebhookClientConfig) *WebhookClientConfigDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &WebhookClientConfigDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *WebhookClientConfigDie) DieFeedPtr(r *admissionregistrationv1.WebhookClientConfig) *WebhookClientConfigDie {
	if r == nil {
		r = &admissionregistrationv1.WebhookClientConfig{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *WebhookClientConfigDie) DieFeedJSON(j []byte) *WebhookClientConfigDie {
	r := admissionregistrationv1.WebhookClientConfig{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *WebhookClientConfigDie) DieFeedYAML(y []byte) *WebhookClientConfigDie {
	r := admissionregistrationv1.WebhookClientConfig{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *WebhookClientConfigDie) DieFeedYAMLFile(name string) *WebhookClientConfigDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *WebhookClientConfigDie) DieFeedRawExtension(raw runtime.RawExtension) *WebhookClientConfigDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *WebhookClientConfigDie) DieRelease() admissionregistrationv1.WebhookClientConfig {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *WebhookClientConfigDie) DieReleasePtr() *admissionregistrationv1.WebhookClientConfig {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *WebhookClientConfigDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *WebhookClientConfigDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *WebhookClientConfigDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *WebhookClientConfigDie) DieStamp(fn func(r *admissionregistrationv1.WebhookClientConfig)) *WebhookClientConfigDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *WebhookClientConfigDie) DieStampAt(jp string, fn interface{}) *WebhookClientConfigDie {
	return d.DieStamp(func(r *admissionregistrationv1.WebhookClientConfig) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *WebhookClientConfigDie) DieWith(fns ...func(d *WebhookClientConfigDie)) *WebhookClientConfigDie {
	nd := WebhookClientConfigBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *WebhookClientConfigDie) DeepCopy() *WebhookClientConfigDie {
	r := *d.r.DeepCopy()
	return &WebhookClientConfigDie{
		mutable: d.mutable,
		r:       r,
	}
}

// `url` gives the location of the webhook, in standard URL form
//
// (`scheme://host:port/path`). Exactly one of `url` or `service`
//
// must be specified.
//
// The `host` should not refer to a service running in the cluster; use
//
// the `service` field instead. The host might be resolved via external
//
// # DNS in some apiservers (e.g., `kube-apiserver` cannot resolve
//
// in-cluster DNS as that would be a layering violation). `host` may
//
// also be an IP address.
//
// # Please note that using `localhost` or `127.0.0.1` as a `host` is
//
// risky unless you take great care to run this webhook on all hosts
//
// which run an apiserver which might need to make calls to this
//
// webhook. Such installs are likely to be non-portable, i.e., not easy
//
// to turn up in a new cluster.
//
// The scheme must be "https"; the URL must begin with "https://".
//
// # A path is optional, and if present may be any string permissible in
//
// a URL. You may use the path to pass an arbitrary string to the
//
// webhook, for example, a cluster identifier.
//
// Attempting to use a user or basic auth e.g. "user:password@" is not
//
// allowed. Fragments ("#...") and query parameters ("?...") are not
//
// allowed, either.
func (d *WebhookClientConfigDie) URL(v *string) *WebhookClientConfigDie {
	return d.DieStamp(func(r *admissionregistrationv1.WebhookClientConfig) {
		r.URL = v
	})
}

// `service` is a reference to the service for this webhook. Either
//
// `service` or `url` must be specified.
//
// If the webhook is running within the cluster, then you should use `service`.
func (d *WebhookClientConfigDie) Service(v *admissionregistrationv1.ServiceReference) *WebhookClientConfigDie {
	return d.DieStamp(func(r *admissionregistrationv1.WebhookClientConfig) {
		r.Service = v
	})
}

// `caBundle` is a PEM encoded CA bundle which will be used to validate the webhook's server certificate.
//
// If unspecified, system trust roots on the apiserver are used.
func (d *WebhookClientConfigDie) CABundle(v []byte) *WebhookClientConfigDie {
	return d.DieStamp(func(r *admissionregistrationv1.WebhookClientConfig) {
		r.CABundle = v
	})
}

var ServiceReferenceBlank = (&ServiceReferenceDie{}).DieFeed(admissionregistrationv1.ServiceReference{})

type ServiceReferenceDie struct {
	mutable bool
	r       admissionregistrationv1.ServiceReference
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ServiceReferenceDie) DieImmutable(immutable bool) *ServiceReferenceDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ServiceReferenceDie) DieFeed(r admissionregistrationv1.ServiceReference) *ServiceReferenceDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ServiceReferenceDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ServiceReferenceDie) DieFeedPtr(r *admissionregistrationv1.ServiceReference) *ServiceReferenceDie {
	if r == nil {
		r = &admissionregistrationv1.ServiceReference{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ServiceReferenceDie) DieFeedJSON(j []byte) *ServiceReferenceDie {
	r := admissionregistrationv1.ServiceReference{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ServiceReferenceDie) DieFeedYAML(y []byte) *ServiceReferenceDie {
	r := admissionregistrationv1.ServiceReference{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ServiceReferenceDie) DieFeedYAMLFile(name string) *ServiceReferenceDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceReferenceDie) DieFeedRawExtension(raw runtime.RawExtension) *ServiceReferenceDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ServiceReferenceDie) DieRelease() admissionregistrationv1.ServiceReference {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ServiceReferenceDie) DieReleasePtr() *admissionregistrationv1.ServiceReference {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ServiceReferenceDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ServiceReferenceDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ServiceReferenceDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ServiceReferenceDie) DieStamp(fn func(r *admissionregistrationv1.ServiceReference)) *ServiceReferenceDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ServiceReferenceDie) DieStampAt(jp string, fn interface{}) *ServiceReferenceDie {
	return d.DieStamp(func(r *admissionregistrationv1.ServiceReference) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ServiceReferenceDie) DieWith(fns ...func(d *ServiceReferenceDie)) *ServiceReferenceDie {
	nd := ServiceReferenceBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ServiceReferenceDie) DeepCopy() *ServiceReferenceDie {
	r := *d.r.DeepCopy()
	return &ServiceReferenceDie{
		mutable: d.mutable,
		r:       r,
	}
}

// `namespace` is the namespace of the service.
//
// Required
func (d *ServiceReferenceDie) Namespace(v string) *ServiceReferenceDie {
	return d.DieStamp(func(r *admissionregistrationv1.ServiceReference) {
		r.Namespace = v
	})
}

// `name` is the name of the service.
//
// Required
func (d *ServiceReferenceDie) Name(v string) *ServiceReferenceDie {
	return d.DieStamp(func(r *admissionregistrationv1.ServiceReference) {
		r.Name = v
	})
}

// `path` is an optional URL path which will be sent in any request to
//
// this service.
func (d *ServiceReferenceDie) Path(v *string) *ServiceReferenceDie {
	return d.DieStamp(func(r *admissionregistrationv1.ServiceReference) {
		r.Path = v
	})
}

// If specified, the port on the service that hosting webhook.
//
// Default to 443 for backward compatibility.
//
// `port` should be a valid port number (1-65535, inclusive).
func (d *ServiceReferenceDie) Port(v *int32) *ServiceReferenceDie {
	return d.DieStamp(func(r *admissionregistrationv1.ServiceReference) {
		r.Port = v
	})
}

var RuleWithOperationsBlank = (&RuleWithOperationsDie{}).DieFeed(admissionregistrationv1.RuleWithOperations{})

type RuleWithOperationsDie struct {
	mutable bool
	r       admissionregistrationv1.RuleWithOperations
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *RuleWithOperationsDie) DieImmutable(immutable bool) *RuleWithOperationsDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *RuleWithOperationsDie) DieFeed(r admissionregistrationv1.RuleWithOperations) *RuleWithOperationsDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &RuleWithOperationsDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *RuleWithOperationsDie) DieFeedPtr(r *admissionregistrationv1.RuleWithOperations) *RuleWithOperationsDie {
	if r == nil {
		r = &admissionregistrationv1.RuleWithOperations{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *RuleWithOperationsDie) DieFeedJSON(j []byte) *RuleWithOperationsDie {
	r := admissionregistrationv1.RuleWithOperations{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *RuleWithOperationsDie) DieFeedYAML(y []byte) *RuleWithOperationsDie {
	r := admissionregistrationv1.RuleWithOperations{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *RuleWithOperationsDie) DieFeedYAMLFile(name string) *RuleWithOperationsDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *RuleWithOperationsDie) DieFeedRawExtension(raw runtime.RawExtension) *RuleWithOperationsDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *RuleWithOperationsDie) DieRelease() admissionregistrationv1.RuleWithOperations {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *RuleWithOperationsDie) DieReleasePtr() *admissionregistrationv1.RuleWithOperations {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *RuleWithOperationsDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *RuleWithOperationsDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *RuleWithOperationsDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *RuleWithOperationsDie) DieStamp(fn func(r *admissionregistrationv1.RuleWithOperations)) *RuleWithOperationsDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *RuleWithOperationsDie) DieStampAt(jp string, fn interface{}) *RuleWithOperationsDie {
	return d.DieStamp(func(r *admissionregistrationv1.RuleWithOperations) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *RuleWithOperationsDie) DieWith(fns ...func(d *RuleWithOperationsDie)) *RuleWithOperationsDie {
	nd := RuleWithOperationsBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *RuleWithOperationsDie) DeepCopy() *RuleWithOperationsDie {
	r := *d.r.DeepCopy()
	return &RuleWithOperationsDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Operations is the operations the admission hook cares about - CREATE, UPDATE, DELETE, CONNECT or *
//
// for all of those operations and any future admission operations that are added.
//
// If '*' is present, the length of the slice must be one.
//
// Required.
func (d *RuleWithOperationsDie) Operations(v ...admissionregistrationv1.OperationType) *RuleWithOperationsDie {
	return d.DieStamp(func(r *admissionregistrationv1.RuleWithOperations) {
		r.Operations = v
	})
}

// Rule is embedded, it describes other criteria of the rule, like
//
// APIGroups, APIVersions, Resources, etc.
func (d *RuleWithOperationsDie) Rule(v admissionregistrationv1.Rule) *RuleWithOperationsDie {
	return d.DieStamp(func(r *admissionregistrationv1.RuleWithOperations) {
		r.Rule = v
	})
}

var RuleBlank = (&RuleDie{}).DieFeed(admissionregistrationv1.Rule{})

type RuleDie struct {
	mutable bool
	r       admissionregistrationv1.Rule
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *RuleDie) DieImmutable(immutable bool) *RuleDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *RuleDie) DieFeed(r admissionregistrationv1.Rule) *RuleDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &RuleDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *RuleDie) DieFeedPtr(r *admissionregistrationv1.Rule) *RuleDie {
	if r == nil {
		r = &admissionregistrationv1.Rule{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *RuleDie) DieFeedJSON(j []byte) *RuleDie {
	r := admissionregistrationv1.Rule{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *RuleDie) DieFeedYAML(y []byte) *RuleDie {
	r := admissionregistrationv1.Rule{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *RuleDie) DieFeedYAMLFile(name string) *RuleDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *RuleDie) DieFeedRawExtension(raw runtime.RawExtension) *RuleDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *RuleDie) DieRelease() admissionregistrationv1.Rule {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *RuleDie) DieReleasePtr() *admissionregistrationv1.Rule {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *RuleDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *RuleDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *RuleDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *RuleDie) DieStamp(fn func(r *admissionregistrationv1.Rule)) *RuleDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *RuleDie) DieStampAt(jp string, fn interface{}) *RuleDie {
	return d.DieStamp(func(r *admissionregistrationv1.Rule) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *RuleDie) DieWith(fns ...func(d *RuleDie)) *RuleDie {
	nd := RuleBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *RuleDie) DeepCopy() *RuleDie {
	r := *d.r.DeepCopy()
	return &RuleDie{
		mutable: d.mutable,
		r:       r,
	}
}

// APIGroups is the API groups the resources belong to. '*' is all groups.
//
// If '*' is present, the length of the slice must be one.
//
// Required.
func (d *RuleDie) APIGroups(v ...string) *RuleDie {
	return d.DieStamp(func(r *admissionregistrationv1.Rule) {
		r.APIGroups = v
	})
}

// APIVersions is the API versions the resources belong to. '*' is all versions.
//
// If '*' is present, the length of the slice must be one.
//
// Required.
func (d *RuleDie) APIVersions(v ...string) *RuleDie {
	return d.DieStamp(func(r *admissionregistrationv1.Rule) {
		r.APIVersions = v
	})
}

// Resources is a list of resources this rule applies to.
//
// For example:
//
// 'pods' means pods.
//
// 'pods/log' means the log subresource of pods.
//
// '*' means all resources, but not subresources.
//
// 'pods/*' means all subresources of pods.
//
// '*/scale' means all scale subresources.
//
// '*/*' means all resources and their subresources.
//
// # If wildcard is present, the validation rule will ensure resources do not
//
// overlap with each other.
//
// Depending on the enclosing object, subresources might not be allowed.
//
// Required.
func (d *RuleDie) Resources(v ...string) *RuleDie {
	return d.DieStamp(func(r *admissionregistrationv1.Rule) {
		r.Resources = v
	})
}

// scope specifies the scope of this rule.
//
// Valid values are "Cluster", "Namespaced", and "*"
//
// "Cluster" means that only cluster-scoped resources will match this rule.
//
// Namespace API objects are cluster-scoped.
//
// "Namespaced" means that only namespaced resources will match this rule.
//
// "*" means that there are no scope restrictions.
//
// Subresources match the scope of their parent resource.
//
// Default is "*".
func (d *RuleDie) Scope(v *admissionregistrationv1.ScopeType) *RuleDie {
	return d.DieStamp(func(r *admissionregistrationv1.Rule) {
		r.Scope = v
	})
}

var MatchConditionBlank = (&MatchConditionDie{}).DieFeed(admissionregistrationv1.MatchCondition{})

type MatchConditionDie struct {
	mutable bool
	r       admissionregistrationv1.MatchCondition
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *MatchConditionDie) DieImmutable(immutable bool) *MatchConditionDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *MatchConditionDie) DieFeed(r admissionregistrationv1.MatchCondition) *MatchConditionDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &MatchConditionDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *MatchConditionDie) DieFeedPtr(r *admissionregistrationv1.MatchCondition) *MatchConditionDie {
	if r == nil {
		r = &admissionregistrationv1.MatchCondition{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *MatchConditionDie) DieFeedJSON(j []byte) *MatchConditionDie {
	r := admissionregistrationv1.MatchCondition{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *MatchConditionDie) DieFeedYAML(y []byte) *MatchConditionDie {
	r := admissionregistrationv1.MatchCondition{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *MatchConditionDie) DieFeedYAMLFile(name string) *MatchConditionDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *MatchConditionDie) DieFeedRawExtension(raw runtime.RawExtension) *MatchConditionDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *MatchConditionDie) DieRelease() admissionregistrationv1.MatchCondition {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *MatchConditionDie) DieReleasePtr() *admissionregistrationv1.MatchCondition {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *MatchConditionDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *MatchConditionDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *MatchConditionDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *MatchConditionDie) DieStamp(fn func(r *admissionregistrationv1.MatchCondition)) *MatchConditionDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *MatchConditionDie) DieStampAt(jp string, fn interface{}) *MatchConditionDie {
	return d.DieStamp(func(r *admissionregistrationv1.MatchCondition) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *MatchConditionDie) DieWith(fns ...func(d *MatchConditionDie)) *MatchConditionDie {
	nd := MatchConditionBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *MatchConditionDie) DeepCopy() *MatchConditionDie {
	r := *d.r.DeepCopy()
	return &MatchConditionDie{
		mutable: d.mutable,
		r:       r,
	}
}

// Name is an identifier for this match condition, used for strategic merging of MatchConditions,
//
// as well as providing an identifier for logging purposes. A good name should be descriptive of
//
// the associated expression.
//
// Name must be a qualified name consisting of alphanumeric characters, '-', '_' or '.', and
//
// must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or
//
// '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]') with an
//
// optional DNS subdomain prefix and '/' (e.g. 'example.com/MyName')
//
// Required.
func (d *MatchConditionDie) Name(v string) *MatchConditionDie {
	return d.DieStamp(func(r *admissionregistrationv1.MatchCondition) {
		r.Name = v
	})
}

// Expression represents the expression which will be evaluated by CEL. Must evaluate to bool.
//
// CEL expressions have access to the contents of the AdmissionRequest and Authorizer, organized into CEL variables:
//
// 'object' - The object from the incoming request. The value is null for DELETE requests.
//
// 'oldObject' - The existing object. The value is null for CREATE requests.
//
// 'request' - Attributes of the admission request(/pkg/apis/admission/types.go#AdmissionRequest).
//
// 'authorizer' - A CEL Authorizer. May be used to perform authorization checks for the principal (user or service account) of the request.
//
// See https://pkg.go.dev/k8s.io/apiserver/pkg/cel/library#Authz
//
// 'authorizer.requestResource' - A CEL ResourceCheck constructed from the 'authorizer' and configured with the
//
// request resource.
//
// Documentation on CEL: https://kubernetes.io/docs/reference/using-api/cel/
//
// Required.
func (d *MatchConditionDie) Expression(v string) *MatchConditionDie {
	return d.DieStamp(func(r *admissionregistrationv1.MatchCondition) {
		r.Expression = v
	})
}

var MutatingWebhookConfigurationBlank = (&MutatingWebhookConfigurationDie{}).DieFeed(admissionregistrationv1.MutatingWebhookConfiguration{})

type MutatingWebhookConfigurationDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       admissionregistrationv1.MutatingWebhookConfiguration
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *MutatingWebhookConfigurationDie) DieImmutable(immutable bool) *MutatingWebhookConfigurationDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *MutatingWebhookConfigurationDie) DieFeed(r admissionregistrationv1.MutatingWebhookConfiguration) *MutatingWebhookConfigurationDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &MutatingWebhookConfigurationDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *MutatingWebhookConfigurationDie) DieFeedPtr(r *admissionregistrationv1.MutatingWebhookConfiguration) *MutatingWebhookConfigurationDie {
	if r == nil {
		r = &admissionregistrationv1.MutatingWebhookConfiguration{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieFeedJSON(j []byte) *MutatingWebhookConfigurationDie {
	r := admissionregistrationv1.MutatingWebhookConfiguration{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieFeedYAML(y []byte) *MutatingWebhookConfigurationDie {
	r := admissionregistrationv1.MutatingWebhookConfiguration{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieFeedYAMLFile(name string) *MutatingWebhookConfigurationDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieFeedRawExtension(raw runtime.RawExtension) *MutatingWebhookConfigurationDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *MutatingWebhookConfigurationDie) DieRelease() admissionregistrationv1.MutatingWebhookConfiguration {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *MutatingWebhookConfigurationDie) DieReleasePtr() *admissionregistrationv1.MutatingWebhookConfiguration {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *MutatingWebhookConfigurationDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *MutatingWebhookConfigurationDie) DieStamp(fn func(r *admissionregistrationv1.MutatingWebhookConfiguration)) *MutatingWebhookConfigurationDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *MutatingWebhookConfigurationDie) DieStampAt(jp string, fn interface{}) *MutatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhookConfiguration) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *MutatingWebhookConfigurationDie) DieWith(fns ...func(d *MutatingWebhookConfigurationDie)) *MutatingWebhookConfigurationDie {
	nd := MutatingWebhookConfigurationBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *MutatingWebhookConfigurationDie) DeepCopy() *MutatingWebhookConfigurationDie {
	r := *d.r.DeepCopy()
	return &MutatingWebhookConfigurationDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*MutatingWebhookConfigurationDie)(nil)

func (d *MutatingWebhookConfigurationDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *MutatingWebhookConfigurationDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *MutatingWebhookConfigurationDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *MutatingWebhookConfigurationDie) UnmarshalJSON(b []byte) error {
	if d == MutatingWebhookConfigurationBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &admissionregistrationv1.MutatingWebhookConfiguration{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *MutatingWebhookConfigurationDie) APIVersion(v string) *MutatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhookConfiguration) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *MutatingWebhookConfigurationDie) Kind(v string) *MutatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhookConfiguration) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *MutatingWebhookConfigurationDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *MutatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhookConfiguration) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// Webhooks is a list of webhooks and the affected resources and operations.
func (d *MutatingWebhookConfigurationDie) Webhooks(v ...admissionregistrationv1.MutatingWebhook) *MutatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhookConfiguration) {
		r.Webhooks = v
	})
}

var MutatingWebhookBlank = (&MutatingWebhookDie{}).DieFeed(admissionregistrationv1.MutatingWebhook{})

type MutatingWebhookDie struct {
	mutable bool
	r       admissionregistrationv1.MutatingWebhook
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *MutatingWebhookDie) DieImmutable(immutable bool) *MutatingWebhookDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *MutatingWebhookDie) DieFeed(r admissionregistrationv1.MutatingWebhook) *MutatingWebhookDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &MutatingWebhookDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *MutatingWebhookDie) DieFeedPtr(r *admissionregistrationv1.MutatingWebhook) *MutatingWebhookDie {
	if r == nil {
		r = &admissionregistrationv1.MutatingWebhook{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *MutatingWebhookDie) DieFeedJSON(j []byte) *MutatingWebhookDie {
	r := admissionregistrationv1.MutatingWebhook{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *MutatingWebhookDie) DieFeedYAML(y []byte) *MutatingWebhookDie {
	r := admissionregistrationv1.MutatingWebhook{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *MutatingWebhookDie) DieFeedYAMLFile(name string) *MutatingWebhookDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *MutatingWebhookDie) DieFeedRawExtension(raw runtime.RawExtension) *MutatingWebhookDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *MutatingWebhookDie) DieRelease() admissionregistrationv1.MutatingWebhook {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *MutatingWebhookDie) DieReleasePtr() *admissionregistrationv1.MutatingWebhook {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *MutatingWebhookDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *MutatingWebhookDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *MutatingWebhookDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *MutatingWebhookDie) DieStamp(fn func(r *admissionregistrationv1.MutatingWebhook)) *MutatingWebhookDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *MutatingWebhookDie) DieStampAt(jp string, fn interface{}) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *MutatingWebhookDie) DieWith(fns ...func(d *MutatingWebhookDie)) *MutatingWebhookDie {
	nd := MutatingWebhookBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *MutatingWebhookDie) DeepCopy() *MutatingWebhookDie {
	r := *d.r.DeepCopy()
	return &MutatingWebhookDie{
		mutable: d.mutable,
		r:       r,
	}
}

// The name of the admission webhook.
//
// # Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where
//
// "imagepolicy" is the name of the webhook, and kubernetes.io is the name
//
// of the organization.
//
// Required.
func (d *MutatingWebhookDie) Name(v string) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.Name = v
	})
}

// ClientConfig defines how to communicate with the hook.
//
// Required
func (d *MutatingWebhookDie) ClientConfig(v admissionregistrationv1.WebhookClientConfig) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.ClientConfig = v
	})
}

// Rules describes what operations on what resources/subresources the webhook cares about.
//
// The webhook cares about an operation if it matches _any_ Rule.
//
// # However, in order to prevent ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks
//
// from putting the cluster in a state which cannot be recovered from without completely
//
// disabling the plugin, ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks are never called
//
// on admission requests for ValidatingWebhookConfiguration and MutatingWebhookConfiguration objects.
func (d *MutatingWebhookDie) Rules(v ...admissionregistrationv1.RuleWithOperations) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.Rules = v
	})
}

// FailurePolicy defines how unrecognized errors from the admission endpoint are handled -
//
// allowed values are Ignore or Fail. Defaults to Fail.
func (d *MutatingWebhookDie) FailurePolicy(v *admissionregistrationv1.FailurePolicyType) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.FailurePolicy = v
	})
}

// matchPolicy defines how the "rules" list is used to match incoming requests.
//
// Allowed values are "Exact" or "Equivalent".
//
// - Exact: match a request only if it exactly matches a specified rule.
//
// For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1,
//
// but "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`,
//
// a request to apps/v1beta1 or extensions/v1beta1 would not be sent to the webhook.
//
// - Equivalent: match a request if modifies a resource listed in rules, even via another API group or version.
//
// For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1,
//
// and "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`,
//
// a request to apps/v1beta1 or extensions/v1beta1 would be converted to apps/v1 and sent to the webhook.
//
// Defaults to "Equivalent"
func (d *MutatingWebhookDie) MatchPolicy(v *admissionregistrationv1.MatchPolicyType) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.MatchPolicy = v
	})
}

// NamespaceSelector decides whether to run the webhook on an object based
//
// on whether the namespace for that object matches the selector. If the
//
// object itself is a namespace, the matching is performed on
//
// object.metadata.labels. If the object is another cluster scoped resource,
//
// it never skips the webhook.
//
// # For example, to run the webhook on any objects whose namespace is not
//
// associated with "runlevel" of "0" or "1";  you will set the selector as
//
// follows:
//
// "namespaceSelector": {
//
// "matchExpressions": [
//
// {
//
// "key": "runlevel",
//
// "operator": "NotIn",
//
// "values": [
//
// "0",
//
// "1"
//
// ]
//
// }
//
// ]
//
// }
//
// # If instead you want to only run the webhook on any objects whose
//
// namespace is associated with the "environment" of "prod" or "staging";
//
// you will set the selector as follows:
//
// "namespaceSelector": {
//
// "matchExpressions": [
//
// {
//
// "key": "environment",
//
// "operator": "In",
//
// "values": [
//
// "prod",
//
// "staging"
//
// ]
//
// }
//
// ]
//
// }
//
// # See
//
// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
//
// for more examples of label selectors.
//
// Default to the empty LabelSelector, which matches everything.
func (d *MutatingWebhookDie) NamespaceSelector(v *apismetav1.LabelSelector) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.NamespaceSelector = v
	})
}

// ObjectSelector decides whether to run the webhook based on if the
//
// object has matching labels. objectSelector is evaluated against both
//
// the oldObject and newObject that would be sent to the webhook, and
//
// is considered to match if either object matches the selector. A null
//
// object (oldObject in the case of create, or newObject in the case of
//
// delete) or an object that cannot have labels (like a
//
// # DeploymentRollback or a PodProxyOptions object) is not considered to
//
// match.
//
// # Use the object selector only if the webhook is opt-in, because end
//
// users may skip the admission webhook by setting the labels.
//
// Default to the empty LabelSelector, which matches everything.
func (d *MutatingWebhookDie) ObjectSelector(v *apismetav1.LabelSelector) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.ObjectSelector = v
	})
}

// SideEffects states whether this webhook has side effects.
//
// Acceptable values are: None, NoneOnDryRun (webhooks created via v1beta1 may also specify Some or Unknown).
//
// # Webhooks with side effects MUST implement a reconciliation system, since a request may be
//
// rejected by a future step in the admission chain and the side effects therefore need to be undone.
//
// # Requests with the dryRun attribute will be auto-rejected if they match a webhook with
//
// sideEffects == Unknown or Some.
func (d *MutatingWebhookDie) SideEffects(v *admissionregistrationv1.SideEffectClass) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.SideEffects = v
	})
}

// TimeoutSeconds specifies the timeout for this webhook. After the timeout passes,
//
// the webhook call will be ignored or the API call will fail based on the
//
// failure policy.
//
// The timeout value must be between 1 and 30 seconds.
//
// Default to 10 seconds.
func (d *MutatingWebhookDie) TimeoutSeconds(v *int32) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.TimeoutSeconds = v
	})
}

// AdmissionReviewVersions is an ordered list of preferred `AdmissionReview`
//
// versions the Webhook expects. API server will try to use first version in
//
// the list which it supports. If none of the versions specified in this list
//
// supported by API server, validation will fail for this object.
//
// # If a persisted webhook configuration specifies allowed versions and does not
//
// include any versions known to the API Server, calls to the webhook will fail
//
// and be subject to the failure policy.
func (d *MutatingWebhookDie) AdmissionReviewVersions(v ...string) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.AdmissionReviewVersions = v
	})
}

// reinvocationPolicy indicates whether this webhook should be called multiple times as part of a single admission evaluation.
//
// Allowed values are "Never" and "IfNeeded".
//
// Never: the webhook will not be called more than once in a single admission evaluation.
//
// IfNeeded: the webhook will be called at least one additional time as part of the admission evaluation
//
// if the object being admitted is modified by other admission plugins after the initial webhook call.
//
// Webhooks that specify this option *must* be idempotent, able to process objects they previously admitted.
//
// Note:
//
// * the number of additional invocations is not guaranteed to be exactly one.
//
// * if additional invocations result in further modifications to the object, webhooks are not guaranteed to be invoked again.
//
// * webhooks that use this option may be reordered to minimize the number of additional invocations.
//
// * to validate an object after all mutations are guaranteed complete, use a validating admission webhook instead.
//
// Defaults to "Never".
func (d *MutatingWebhookDie) ReinvocationPolicy(v *admissionregistrationv1.ReinvocationPolicyType) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.ReinvocationPolicy = v
	})
}

// MatchConditions is a list of conditions that must be met for a request to be sent to this
//
// webhook. Match conditions filter requests that have already been matched by the rules,
//
// namespaceSelector, and objectSelector. An empty list of matchConditions matches all requests.
//
// There are a maximum of 64 match conditions allowed.
//
// The exact matching logic is (in order):
//
// 1. If ANY matchCondition evaluates to FALSE, the webhook is skipped.
//
// 2. If ALL matchConditions evaluate to TRUE, the webhook is called.
//
// 3. If any matchCondition evaluates to an error (but none are FALSE):
//
// - If failurePolicy=Fail, reject the request
//
// - If failurePolicy=Ignore, the error is ignored and the webhook is skipped
//
// This is a beta feature and managed by the AdmissionWebhookMatchConditions feature gate.
func (d *MutatingWebhookDie) MatchConditions(v ...admissionregistrationv1.MatchCondition) *MutatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.MutatingWebhook) {
		r.MatchConditions = v
	})
}

var ValidatingWebhookConfigurationBlank = (&ValidatingWebhookConfigurationDie{}).DieFeed(admissionregistrationv1.ValidatingWebhookConfiguration{})

type ValidatingWebhookConfigurationDie struct {
	metav1.FrozenObjectMeta
	mutable bool
	r       admissionregistrationv1.ValidatingWebhookConfiguration
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ValidatingWebhookConfigurationDie) DieImmutable(immutable bool) *ValidatingWebhookConfigurationDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ValidatingWebhookConfigurationDie) DieFeed(r admissionregistrationv1.ValidatingWebhookConfiguration) *ValidatingWebhookConfigurationDie {
	if d.mutable {
		d.FrozenObjectMeta = metav1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ValidatingWebhookConfigurationDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ValidatingWebhookConfigurationDie) DieFeedPtr(r *admissionregistrationv1.ValidatingWebhookConfiguration) *ValidatingWebhookConfigurationDie {
	if r == nil {
		r = &admissionregistrationv1.ValidatingWebhookConfiguration{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieFeedJSON(j []byte) *ValidatingWebhookConfigurationDie {
	r := admissionregistrationv1.ValidatingWebhookConfiguration{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieFeedYAML(y []byte) *ValidatingWebhookConfigurationDie {
	r := admissionregistrationv1.ValidatingWebhookConfiguration{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieFeedYAMLFile(name string) *ValidatingWebhookConfigurationDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieFeedRawExtension(raw runtime.RawExtension) *ValidatingWebhookConfigurationDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ValidatingWebhookConfigurationDie) DieRelease() admissionregistrationv1.ValidatingWebhookConfiguration {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ValidatingWebhookConfigurationDie) DieReleasePtr() *admissionregistrationv1.ValidatingWebhookConfiguration {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ValidatingWebhookConfigurationDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ValidatingWebhookConfigurationDie) DieStamp(fn func(r *admissionregistrationv1.ValidatingWebhookConfiguration)) *ValidatingWebhookConfigurationDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ValidatingWebhookConfigurationDie) DieStampAt(jp string, fn interface{}) *ValidatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhookConfiguration) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ValidatingWebhookConfigurationDie) DieWith(fns ...func(d *ValidatingWebhookConfigurationDie)) *ValidatingWebhookConfigurationDie {
	nd := ValidatingWebhookConfigurationBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ValidatingWebhookConfigurationDie) DeepCopy() *ValidatingWebhookConfigurationDie {
	r := *d.r.DeepCopy()
	return &ValidatingWebhookConfigurationDie{
		FrozenObjectMeta: metav1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
	}
}

var _ runtime.Object = (*ValidatingWebhookConfigurationDie)(nil)

func (d *ValidatingWebhookConfigurationDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *ValidatingWebhookConfigurationDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ValidatingWebhookConfigurationDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ValidatingWebhookConfigurationDie) UnmarshalJSON(b []byte) error {
	if d == ValidatingWebhookConfigurationBlank {
		return fmtx.Errorf("cannot unmarshal into the blank die, create a copy first")
	}
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	r := &admissionregistrationv1.ValidatingWebhookConfiguration{}
	err := json.Unmarshal(b, r)
	*d = *d.DieFeed(*r)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *ValidatingWebhookConfigurationDie) APIVersion(v string) *ValidatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhookConfiguration) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *ValidatingWebhookConfigurationDie) Kind(v string) *ValidatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhookConfiguration) {
		r.Kind = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *ValidatingWebhookConfigurationDie) MetadataDie(fn func(d *metav1.ObjectMetaDie)) *ValidatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhookConfiguration) {
		d := metav1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// Webhooks is a list of webhooks and the affected resources and operations.
func (d *ValidatingWebhookConfigurationDie) Webhooks(v ...admissionregistrationv1.ValidatingWebhook) *ValidatingWebhookConfigurationDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhookConfiguration) {
		r.Webhooks = v
	})
}

var ValidatingWebhookBlank = (&ValidatingWebhookDie{}).DieFeed(admissionregistrationv1.ValidatingWebhook{})

type ValidatingWebhookDie struct {
	mutable bool
	r       admissionregistrationv1.ValidatingWebhook
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ValidatingWebhookDie) DieImmutable(immutable bool) *ValidatingWebhookDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ValidatingWebhookDie) DieFeed(r admissionregistrationv1.ValidatingWebhook) *ValidatingWebhookDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ValidatingWebhookDie{
		mutable: d.mutable,
		r:       r,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ValidatingWebhookDie) DieFeedPtr(r *admissionregistrationv1.ValidatingWebhook) *ValidatingWebhookDie {
	if r == nil {
		r = &admissionregistrationv1.ValidatingWebhook{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ValidatingWebhookDie) DieFeedJSON(j []byte) *ValidatingWebhookDie {
	r := admissionregistrationv1.ValidatingWebhook{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ValidatingWebhookDie) DieFeedYAML(y []byte) *ValidatingWebhookDie {
	r := admissionregistrationv1.ValidatingWebhook{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ValidatingWebhookDie) DieFeedYAMLFile(name string) *ValidatingWebhookDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ValidatingWebhookDie) DieFeedRawExtension(raw runtime.RawExtension) *ValidatingWebhookDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ValidatingWebhookDie) DieRelease() admissionregistrationv1.ValidatingWebhook {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ValidatingWebhookDie) DieReleasePtr() *admissionregistrationv1.ValidatingWebhook {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ValidatingWebhookDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ValidatingWebhookDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ValidatingWebhookDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ValidatingWebhookDie) DieStamp(fn func(r *admissionregistrationv1.ValidatingWebhook)) *ValidatingWebhookDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ValidatingWebhookDie) DieStampAt(jp string, fn interface{}) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ValidatingWebhookDie) DieWith(fns ...func(d *ValidatingWebhookDie)) *ValidatingWebhookDie {
	nd := ValidatingWebhookBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ValidatingWebhookDie) DeepCopy() *ValidatingWebhookDie {
	r := *d.r.DeepCopy()
	return &ValidatingWebhookDie{
		mutable: d.mutable,
		r:       r,
	}
}

// The name of the admission webhook.
//
// # Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where
//
// "imagepolicy" is the name of the webhook, and kubernetes.io is the name
//
// of the organization.
//
// Required.
func (d *ValidatingWebhookDie) Name(v string) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.Name = v
	})
}

// ClientConfig defines how to communicate with the hook.
//
// Required
func (d *ValidatingWebhookDie) ClientConfig(v admissionregistrationv1.WebhookClientConfig) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.ClientConfig = v
	})
}

// Rules describes what operations on what resources/subresources the webhook cares about.
//
// The webhook cares about an operation if it matches _any_ Rule.
//
// # However, in order to prevent ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks
//
// from putting the cluster in a state which cannot be recovered from without completely
//
// disabling the plugin, ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks are never called
//
// on admission requests for ValidatingWebhookConfiguration and MutatingWebhookConfiguration objects.
func (d *ValidatingWebhookDie) Rules(v ...admissionregistrationv1.RuleWithOperations) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.Rules = v
	})
}

// FailurePolicy defines how unrecognized errors from the admission endpoint are handled -
//
// allowed values are Ignore or Fail. Defaults to Fail.
func (d *ValidatingWebhookDie) FailurePolicy(v *admissionregistrationv1.FailurePolicyType) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.FailurePolicy = v
	})
}

// matchPolicy defines how the "rules" list is used to match incoming requests.
//
// Allowed values are "Exact" or "Equivalent".
//
// - Exact: match a request only if it exactly matches a specified rule.
//
// For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1,
//
// but "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`,
//
// a request to apps/v1beta1 or extensions/v1beta1 would not be sent to the webhook.
//
// - Equivalent: match a request if modifies a resource listed in rules, even via another API group or version.
//
// For example, if deployments can be modified via apps/v1, apps/v1beta1, and extensions/v1beta1,
//
// and "rules" only included `apiGroups:["apps"], apiVersions:["v1"], resources: ["deployments"]`,
//
// a request to apps/v1beta1 or extensions/v1beta1 would be converted to apps/v1 and sent to the webhook.
//
// Defaults to "Equivalent"
func (d *ValidatingWebhookDie) MatchPolicy(v *admissionregistrationv1.MatchPolicyType) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.MatchPolicy = v
	})
}

// NamespaceSelector decides whether to run the webhook on an object based
//
// on whether the namespace for that object matches the selector. If the
//
// object itself is a namespace, the matching is performed on
//
// object.metadata.labels. If the object is another cluster scoped resource,
//
// it never skips the webhook.
//
// # For example, to run the webhook on any objects whose namespace is not
//
// associated with "runlevel" of "0" or "1";  you will set the selector as
//
// follows:
//
// "namespaceSelector": {
//
// "matchExpressions": [
//
// {
//
// "key": "runlevel",
//
// "operator": "NotIn",
//
// "values": [
//
// "0",
//
// "1"
//
// ]
//
// }
//
// ]
//
// }
//
// # If instead you want to only run the webhook on any objects whose
//
// namespace is associated with the "environment" of "prod" or "staging";
//
// you will set the selector as follows:
//
// "namespaceSelector": {
//
// "matchExpressions": [
//
// {
//
// "key": "environment",
//
// "operator": "In",
//
// "values": [
//
// "prod",
//
// "staging"
//
// ]
//
// }
//
// ]
//
// }
//
// # See
//
// https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
//
// for more examples of label selectors.
//
// Default to the empty LabelSelector, which matches everything.
func (d *ValidatingWebhookDie) NamespaceSelector(v *apismetav1.LabelSelector) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.NamespaceSelector = v
	})
}

// ObjectSelector decides whether to run the webhook based on if the
//
// object has matching labels. objectSelector is evaluated against both
//
// the oldObject and newObject that would be sent to the webhook, and
//
// is considered to match if either object matches the selector. A null
//
// object (oldObject in the case of create, or newObject in the case of
//
// delete) or an object that cannot have labels (like a
//
// # DeploymentRollback or a PodProxyOptions object) is not considered to
//
// match.
//
// # Use the object selector only if the webhook is opt-in, because end
//
// users may skip the admission webhook by setting the labels.
//
// Default to the empty LabelSelector, which matches everything.
func (d *ValidatingWebhookDie) ObjectSelector(v *apismetav1.LabelSelector) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.ObjectSelector = v
	})
}

// SideEffects states whether this webhook has side effects.
//
// Acceptable values are: None, NoneOnDryRun (webhooks created via v1beta1 may also specify Some or Unknown).
//
// # Webhooks with side effects MUST implement a reconciliation system, since a request may be
//
// rejected by a future step in the admission chain and the side effects therefore need to be undone.
//
// # Requests with the dryRun attribute will be auto-rejected if they match a webhook with
//
// sideEffects == Unknown or Some.
func (d *ValidatingWebhookDie) SideEffects(v *admissionregistrationv1.SideEffectClass) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.SideEffects = v
	})
}

// TimeoutSeconds specifies the timeout for this webhook. After the timeout passes,
//
// the webhook call will be ignored or the API call will fail based on the
//
// failure policy.
//
// The timeout value must be between 1 and 30 seconds.
//
// Default to 10 seconds.
func (d *ValidatingWebhookDie) TimeoutSeconds(v *int32) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.TimeoutSeconds = v
	})
}

// AdmissionReviewVersions is an ordered list of preferred `AdmissionReview`
//
// versions the Webhook expects. API server will try to use first version in
//
// the list which it supports. If none of the versions specified in this list
//
// supported by API server, validation will fail for this object.
//
// # If a persisted webhook configuration specifies allowed versions and does not
//
// include any versions known to the API Server, calls to the webhook will fail
//
// and be subject to the failure policy.
func (d *ValidatingWebhookDie) AdmissionReviewVersions(v ...string) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.AdmissionReviewVersions = v
	})
}

// MatchConditions is a list of conditions that must be met for a request to be sent to this
//
// webhook. Match conditions filter requests that have already been matched by the rules,
//
// namespaceSelector, and objectSelector. An empty list of matchConditions matches all requests.
//
// There are a maximum of 64 match conditions allowed.
//
// The exact matching logic is (in order):
//
// 1. If ANY matchCondition evaluates to FALSE, the webhook is skipped.
//
// 2. If ALL matchConditions evaluate to TRUE, the webhook is called.
//
// 3. If any matchCondition evaluates to an error (but none are FALSE):
//
// - If failurePolicy=Fail, reject the request
//
// - If failurePolicy=Ignore, the error is ignored and the webhook is skipped
//
// This is a beta feature and managed by the AdmissionWebhookMatchConditions feature gate.
func (d *ValidatingWebhookDie) MatchConditions(v ...admissionregistrationv1.MatchCondition) *ValidatingWebhookDie {
	return d.DieStamp(func(r *admissionregistrationv1.ValidatingWebhook) {
		r.MatchConditions = v
	})
}
