//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2021-2022 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package v1

import (
	testing "reconciler.io/dies/testing"
	testingx "testing"
)

func TestWebhookClientConfigDie_MissingMethods(t *testingx.T) {
	die := WebhookClientConfigBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for WebhookClientConfigDie: %s", diff.List())
	}
}

func TestServiceReferenceDie_MissingMethods(t *testingx.T) {
	die := ServiceReferenceBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ServiceReferenceDie: %s", diff.List())
	}
}

func TestRuleWithOperationsDie_MissingMethods(t *testingx.T) {
	die := RuleWithOperationsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RuleWithOperationsDie: %s", diff.List())
	}
}

func TestRuleDie_MissingMethods(t *testingx.T) {
	die := RuleBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for RuleDie: %s", diff.List())
	}
}

func TestMatchConditionDie_MissingMethods(t *testingx.T) {
	die := MatchConditionBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for MatchConditionDie: %s", diff.List())
	}
}

func TestMutatingWebhookConfigurationDie_MissingMethods(t *testingx.T) {
	die := MutatingWebhookConfigurationBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for MutatingWebhookConfigurationDie: %s", diff.List())
	}
}

func TestMutatingWebhookDie_MissingMethods(t *testingx.T) {
	die := MutatingWebhookBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for MutatingWebhookDie: %s", diff.List())
	}
}

func TestValidatingAdmissionPolicyDie_MissingMethods(t *testingx.T) {
	die := ValidatingAdmissionPolicyBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingAdmissionPolicyDie: %s", diff.List())
	}
}

func TestValidatingAdmissionPolicySpecDie_MissingMethods(t *testingx.T) {
	die := ValidatingAdmissionPolicySpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingAdmissionPolicySpecDie: %s", diff.List())
	}
}

func TestParamKindDie_MissingMethods(t *testingx.T) {
	die := ParamKindBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ParamKindDie: %s", diff.List())
	}
}

func TestMatchResourcesDie_MissingMethods(t *testingx.T) {
	die := MatchResourcesBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for MatchResourcesDie: %s", diff.List())
	}
}

func TestNamedRuleWithOperationsDie_MissingMethods(t *testingx.T) {
	die := NamedRuleWithOperationsBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for NamedRuleWithOperationsDie: %s", diff.List())
	}
}

func TestValidationDie_MissingMethods(t *testingx.T) {
	die := ValidationBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidationDie: %s", diff.List())
	}
}

func TestAuditAnnotationDie_MissingMethods(t *testingx.T) {
	die := AuditAnnotationBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for AuditAnnotationDie: %s", diff.List())
	}
}

func TestVariableDie_MissingMethods(t *testingx.T) {
	die := VariableBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for VariableDie: %s", diff.List())
	}
}

func TestValidatingAdmissionPolicyStatusDie_MissingMethods(t *testingx.T) {
	die := ValidatingAdmissionPolicyStatusBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingAdmissionPolicyStatusDie: %s", diff.List())
	}
}

func TestTypeCheckingDie_MissingMethods(t *testingx.T) {
	die := TypeCheckingBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for TypeCheckingDie: %s", diff.List())
	}
}

func TestExpressionWarningDie_MissingMethods(t *testingx.T) {
	die := ExpressionWarningBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ExpressionWarningDie: %s", diff.List())
	}
}

func TestValidatingAdmissionPolicyBindingDie_MissingMethods(t *testingx.T) {
	die := ValidatingAdmissionPolicyBindingBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingAdmissionPolicyBindingDie: %s", diff.List())
	}
}

func TestValidatingAdmissionPolicyBindingSpecDie_MissingMethods(t *testingx.T) {
	die := ValidatingAdmissionPolicyBindingSpecBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingAdmissionPolicyBindingSpecDie: %s", diff.List())
	}
}

func TestParamRefDie_MissingMethods(t *testingx.T) {
	die := ParamRefBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ParamRefDie: %s", diff.List())
	}
}

func TestValidatingWebhookConfigurationDie_MissingMethods(t *testingx.T) {
	die := ValidatingWebhookConfigurationBlank
	ignore := []string{"TypeMeta", "ObjectMeta"}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingWebhookConfigurationDie: %s", diff.List())
	}
}

func TestValidatingWebhookDie_MissingMethods(t *testingx.T) {
	die := ValidatingWebhookBlank
	ignore := []string{}
	diff := testing.DieFieldDiff(die).Delete(ignore...)
	if diff.Len() != 0 {
		t.Errorf("found missing fields for ValidatingWebhookDie: %s", diff.List())
	}
}
